Repository cometbft/cometbft, pull requests merged in 2023-03, with the labels that each got.

#422 docs: Bump Go version for v0.37.x in readme on main
  README.md
Labels: documentation, automerge

#375 Improve wait for node in e2e runner for long catch-up times
  state/txindex/indexer_service.go
  test/e2e/Makefile
  test/e2e/networks/long.toml
  test/e2e/pkg/testnet.go
  test/e2e/runner/rpc.go
  test/e2e/runner/wait.go
Labels: qa, backport-to-v0.37.x, rename

#434 ci: Enforce release version check when pushing tags
  .github/workflows/pre-release.yml
  .github/workflows/release-version.yml
  .github/workflows/release.yml
Labels: automerge, backport-to-v0.34.x, backport-to-v0.37.x, ci

#425 (preliminarily) add long-running weekly e2e workflow
  .github/workflows/e2e-long-main.yml
Labels: qa, backport-to-v0.37.x

#431 Release v0.37.0-rc4
  version/version.go
Labels: release

#438 Update go-built-in.md
  docs/tutorials/go-built-in.md
Labels: backport-to-v0.34.x, backport-to-v0.37.x

#432 e2e: fix Makefile to produce commit_hash for builtin
  Makefile
  common.mk
  test/e2e/Makefile
Labels: bug

#450 Migrate RFC 017 to RFC 100
  docs/rfc/README.md
  docs/rfc/rfc-100-abci-vote-extension-propag.md
Labels: documentation, abci

#421 spec:ABCI2.0 - Uncommenting content related to vote xtensions and finalize block
  spec/abci/abci++_app_requirements.md
  spec/abci/abci++_basic_concepts.md
  spec/abci/abci++_comet_expected_behavior.md
  spec/abci/abci++_methods.md
Labels: spec

#415 config: remove `block_sync` key
  cmd/cometbft/commands/run_node.go
  config/config.go
  config/toml.go
  config/toml_test.go
  docs/core/block-sync.md
  docs/core/configuration.md
  node/node.go
  node/setup.go
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
Labels: block-sync, breaking

#414 config: mark `block_sync` key as deprecated
  .changelog/unreleased/breaking-changes/409-deprecate-blocksyncmode
  config/config.go
  config/toml.go
  docs/core/configuration.md
  node/node.go
  test/e2e/pkg/manifest.go
Labels: block-sync

#451 RFC100: Upgrade path section
  docs/rfc/rfc-100-abci-vote-extension-propag.md
Labels: abci

#455 ci: Remove Markdown link checker
  .github/workflows/markdown-links.yml
Labels: automerge, ci

#453 Backport small fix to ABCI 1.0 spec
  spec/abci/abci++_methods.md
Labels: abci

#471 Backport vote extension metrics
  consensus/metrics.gen.go
  consensus/metrics.go
  consensus/state.go
  docs/core/metrics.md
  state/metrics.gen.go
  state/metrics.go
Labels: abci

#478 Move `apphash`from `Commit`to `FinalizeBlock` (leftovers)
  .changelog/unreleased/breaking-changes/8664-move-app-hash-to-commit.md
  UPGRADING.md
  abci/tests/test_cli/ex1.abci
  abci/tests/test_cli/ex1.abci.out
  abci/tests/test_cli/test.sh
  consensus/mempool_test.go
  docs/app-dev/abci-cli.md
  spec/abci/abci++_methods.md
  state/execution.go
Labels: abci

#467 Move `mempoolIDs` back to `mempool/ids.go`
  mempool/ids.go
  mempool/ids_test.go
  mempool/reactor.go
  mempool/reactor_test.go
Labels: mempool

#496 ABCI calls should crash/exit in all cases when the call itself reports and error
  .changelog/unreleased/bug-fixes/496-error-on-applyblock-should-panic.md
  .github/workflows/govulncheck.yml
  consensus/state.go
  state/execution.go
Labels: abci, backport-to-v0.34.x, backport-to-v0.37.x

#488 Compare `types.proto` and `feature/abci++vef` and tip of `v0.36.x`
  .github/workflows/govulncheck.yml
  UPGRADING.md
  abci/cmd/abci-cli/abci-cli.go
  abci/example/kvstore/kvstore.go
  abci/tests/server/client.go
  abci/types/types.pb.go
  consensus/mempool_test.go
  consensus/replay.go
  consensus/replay_test.go
  consensus/state_test.go
  mempool/clist_mempool_test.go
  proto/tendermint/abci/types.proto
  rpc/core/types/responses.go
  state/execution.go
  state/helpers_test.go
  state/state_test.go
  state/store.go
  test/e2e/app/app.go
Labels: abci

#511 Votes can't have zero height
  types/vote_test.go
Labels: bug

#513 Votes can't have zero height
  .github/workflows/govulncheck.yml
  types/vote.go
  types/vote_test.go
Labels: bug

#512 Votes can't have zero height
  .github/workflows/govulncheck.yml
  types/vote.go
  types/vote_test.go
Labels: bug

#525 Update README.md
  spec/README.md
Labels: backport-to-v0.34.x, backport-to-v0.37.x

#526 fix(readme.md): update the links for guides
  README.md
  docs/guides/quick-start.md
Labels: backport-to-v0.37.x

#489 Pass signatures of vote extensions in `RequestPrepareProposal`
  abci/types/types.pb.go
  consensus/state_test.go
  proto/tendermint/abci/types.proto
  state/execution.go
  test/e2e/app/app.go
  test/e2e/networks/ci.toml
  test/e2e/pkg/testnet.go
  test/e2e/tests/app_test.go
Labels: abci

#514 ABCI 2.0: Double-check that `PreparaProposal` and `ProcessProposal` respect coherence all over our code
  abci/example/kvstore/kvstore.go
  state/execution.go
  state/helpers_test.go
  test/e2e/app/app.go
Labels: abci

#539 Fix bugs: (1) infinite loop in e2e tests (2) missing Vote Extensions at `PrepareProposal` time
  consensus/state.go
  test/e2e/runner/rpc.go
Labels: abci

#509 Tighten the checks we do on vote extensions in e2e app
  state/execution.go
  test/e2e/app/app.go
Labels: abci

#469 spec:abci2.0 - clarify crash recovery mechanism
  spec/abci/abci++_app_requirements.md
Labels: abci, spec

#540 Fix deficiency in ABCI interface: `SignedLastBlock`
  abci/types/types.pb.go
  proto/tendermint/abci/types.proto
  proto/tendermint/types/types.pb.go
  proto/tendermint/types/types.proto
  proto/tendermint/types/validator.pb.go
  proto/tendermint/types/validator.proto
  state/execution.go
  state/execution_test.go
  test/e2e/app/app.go
Labels: abci

#542 Fix bugs: (1) another infinite loop in e2e tests (2) missing validator info from genesis
  test/e2e/app/app.go
  test/e2e/runner/rpc.go
Labels: abci

#534 docs: improve Execute code block
  spec/core/data_structures.md
Labels: backport-to-v0.34.x, backport-to-v0.37.x

#562 Fixed two bugs related to metrics
  consensus/metrics.gen.go
  consensus/metrics.go
  proxy/app_conn.go
  scripts/qa/reporting/latency_plotter.py
  scripts/qa/reporting/prometheus_plotter.py
  test/e2e/networks/ci.toml
Labels: abci

#423 kvindexer: porting event sequences and slash parsing to main
  .changelog/unreleased/bug-fixes/423-forwardport-default-kvindexer-behaviour.md
  abci/example/kvstore/kvstore.go
  abci/example/kvstore/persistent_kvstore.go
  docs/app-dev/indexing-transactions.md
  rpc/client/main_test.go
  rpc/client/rpc_test.go
  state/indexer/block/kv/kv.go
  state/indexer/block/kv/kv_test.go
  state/indexer/block/kv/util.go
  state/indexer/query_range.go
  state/txindex/kv/kv.go
  state/txindex/kv/kv_test.go
  state/txindex/kv/utils.go
Labels: indexer

#477 Simplify removing txs in mempool
  mempool/clist_mempool.go
Labels: mempool

#536 Fixes the order of guides and removes stale guides
  docs/guides/go-built-in.md
  docs/guides/go.md
  docs/guides/install.md
  docs/guides/java.md
  docs/guides/kotlin.md
  docs/guides/upgrading-from-tm.md
Labels: automerge

#545 Update description of profobuf definitions in the doc
  spec/abci/abci++_methods.md
  spec/core/data_structures.md
  spec/p2p/messages/block-sync.md
Labels: abci

#538 Add metrics to BlockSync
  .changelog/unreleased/improvements/543-metrics-for-blocksync.md
  blocksync/metrics.gen.go
  blocksync/metrics.go
  blocksync/reactor.go
  consensus/metrics.go
Labels: metrics, block-sync

#484 spec: abci2.0 -Incorporate content of RFC100 into the spec
  spec/abci/abci++_app_requirements.md
  spec/abci/abci++_comet_expected_behavior.md
Labels: abci, spec

#563 e2e: add prometheus flag to Generator CLI
  .github/workflows/e2e-manual-multiversion.yml
  .github/workflows/e2e-manual.yml
  .github/workflows/e2e-nightly-34x.yml
  .github/workflows/e2e-nightly-37x.yml
  .github/workflows/e2e-nightly-main.yml
  test/e2e/generator/generate.go
  test/e2e/generator/main.go
Labels: metrics, backport-to-v0.34.x, backport-to-v0.37.x

#78 rfc: Banning peers based on ResponseCheckTx
  docs/rfc/README.md
  docs/rfc/rfc-101-p2p-bad-peers-checktx.md
  docs/rfc/tendermint-core/README.md
  docs/rfc/tendermint-core/rfc-026-p2p-bad-peers-checktx.md
Labels: documentation, mempool, p2p, wip
