Repository cometbft/cometbft, pull requests merged in 2023-04, with the labels that each got.

#468 Remove unused `TxsMessage` in mempool
  mempool/reactor.go
  spec/p2p/messages/mempool.md
Labels: mempool

#583 Update SECURITY.md
  SECURITY.md
Labels: automerge

#651 Mark the gRPC broadcast API as deprecated
  node/node.go
  proto/tendermint/rpc/grpc/types.proto
  rpc/grpc/client_server.go
  rpc/test/helpers.go
  test/app/grpc_client.go
Labels: backport-to-v0.38.x

#661 ci: Bump Go version for govulncheck to v1.20.3
  .github/workflows/govulncheck.yml
Labels: backport-to-v0.37.x, ci, backport-to-v0.38.x

#662 ci: Bump Go version for govulncheck to v1.19.8
  .github/workflows/govulncheck.yml
Labels: ci

#663 docs: fix wscat invocation and add TLS note
  docs/core/subscription.md
Labels: documentation, backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x

#626 cmd: Remove snake case deprecation warning
  cmd/cometbft/commands/compact.go
  cmd/cometbft/commands/gen_node_key.go
  cmd/cometbft/commands/gen_validator.go
  cmd/cometbft/commands/probe_upnp.go
  cmd/cometbft/commands/reindex_event.go
  cmd/cometbft/commands/replay.go
  cmd/cometbft/commands/reset.go
  cmd/cometbft/commands/root.go
  cmd/cometbft/commands/show_node_id.go
  cmd/cometbft/commands/show_validator.go
Labels: backport-to-v0.34.x, backport-to-v0.37.x, tech-debt, backport-to-v0.38.x

#660 Update contributing to draft PRS
  CONTRIBUTING.md
Labels: documentation

#655 SECURITY.md: Fix broken advisory reporting link and format document
  SECURITY.md
Labels: documentation, security

#685 Update govulncheck.yml
  .github/workflows/govulncheck.yml
Labels: backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x

#692 Fix race condition in `gossipVotesRoutine`
  consensus/reactor.go
  test/e2e/Makefile
  test/e2e/docker/Dockerfile
Labels: bug, backport-to-v0.38.x

#688 Fill time in `FinalizeBlock`
  state/execution.go
  state/execution_test.go
  state/helpers_test.go
Labels: bug, abci, backport-to-v0.38.x

#577 light client: Address panic in response to empty signed header
  light/provider/http/http.go
  types/light.go
Labels: automerge, backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x

#638 Add more debugging data for bad http responses
  .changelog/unreleased/improvements/638-json-rpc-error-message.md
  rpc/jsonrpc/client/http_json_client.go
Labels: rpc, automerge, backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x

#558 crypto/merkle: Add error handling
  .changelog/unreleased/breaking-changes/558-tm10011.md
  crypto/merkle/proof.go
  crypto/merkle/proof_test.go
  crypto/merkle/proof_value.go
Labels: backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x

#713 e2e: Add thread-safe getters to app state
  test/e2e/app/app.go
  test/e2e/app/snapshots.go
  test/e2e/app/state.go
Labels: backport-to-v0.38.x

#746 Fill `time` field in `ExecCommitBlock`
  state/execution.go
  state/execution_test.go
Labels: bug, backport-to-v0.38.x

#740 Update contributing guidelines
  CONTRIBUTING.md
  docs/imgs/contributing.png
Labels: documentation, automerge

#755 Fix `TestStateOversizedBlock`
  consensus/state_test.go
Labels: bug, backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x

#757 Release v0.37.1
  .changelog/v0.37.1/breaking-changes/558-tm10011.md
  .changelog/v0.37.1/bug-fixes/496-error-on-applyblock-should-panic.md
  .changelog/v0.37.1/bug-fixes/524-rename-peerstate-tojson.md
  .changelog/v0.37.1/bug-fixes/575-fix-light-client-panic.md
  .changelog/v0.37.1/improvements/638-json-rpc-error-message.md
  .changelog/v0.37.1/summary.md
  CHANGELOG.md
  UPGRADING.md
  version/version.go
Labels: release

#581 kvindexer: Removing event function type as it is always the same
  state/indexer/block/kv/kv.go
  state/indexer/block/kv/kv_test.go
  state/indexer/block/kv/util.go
  state/txindex/kv/kv_test.go
Labels: indexer, storage, backport-to-v0.38.x
