Repository cometbft/cometbft, pull requests merged in 2023-09, with the labels that each got.

#1284 evidence: export errors
  evidence/errors.go
  evidence/pool.go
  evidence/pool_test.go
  evidence/reactor.go
  evidence/verify.go
  node/node.go
  state/errors.go
  types/evidence.go
Labels: enhancement, evidence

#1295 Re-implement removal of genesis persistence in state db
  .changelog/unreleased/improvements/1017-remove-genesis-persistence-in-state-db.md
  node/node_test.go
  node/setup.go
Labels: storage, P:storage-optimization

#1293 node: verify genesis doc hash against the file contents rather than remarshalled JSON
  .changelog/unreleased/breaking-changes/1287-genesis-doc-hash-from-file.md
  node/setup.go
Labels: breaking

#1270 Provide relevant block data in `ExtendVote`
  .changelog/unreleased/breaking-changes/1270-executor_extend_vote.md
  abci/types/types.pb.go
  consensus/byzantine_test.go
  consensus/state.go
  consensus/state_test.go
  proto/tendermint/abci/types.proto
  spec/abci/abci++_methods.md
  state/execution.go
Labels: enhancement, abci, backport-to-v0.38.x

#1057 node/state:bootstrap state api
  .changelog/unreleased/breaking-changes/1057-bootstrap-state-api.md
  .changelog/unreleased/features/1057-bootstrap-state-api.md
  blocksync/reactor.go
  blocksync/reactor_test.go
  consensus/state.go
  node/node.go
  node/setup.go
  state/export_test.go
  state/mocks/store.go
  state/store.go
  state/store_test.go
  store/store.go
Labels: state, state-sync, wip, backport-to-v0.38.x

#1323 Fix race condition in `gossipVotesRoutine`
  consensus/reactor.go
Labels: bug, backport-to-v0.38.x

#1297 state: remove genesis file from database
  .changelog/unreleased/improvements/1297-remove-genesis-from-db-upgrade.md
  node/node.go
  node/node_test.go
  node/setup.go
Labels: P:storage-optimization

#1335 Added changelog for pruning metrics
  .changelog/unreleased/features/1234-pruning-metrics.md
Labels: metrics

#1336 Add `.md` extension to vote extensions changelog
  .changelog/unreleased/features/9836-abci-add-vote-extension.md
Labels: abci

#1338 rpc: add finalize_block_events to rpc doc
  rpc/openapi/openapi.yaml
Labels: backport-to-v0.38.x

#1329 Fix typo: exent -> event
  state/txindex/indexer_service.go
Labels: backport-to-v0.34.x

#1257 consensus: test for precommit/locking corner case
  consensus/state_test.go
Labels: consensus, backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x

#1334 TxIndexer and BlockIndexer pruning metrics
  .changelog/unreleased/features/1334-metrics-for-index-pruning.md
  state/metrics.gen.go
  state/metrics.go
  state/pruner.go
Labels: metrics, storage

#1352 Update Go version specified in root README on main for `v0.34.x`
  README.md
Labels: chore

#1349 Add test/e2e/data to gitignore
  .gitignore
Labels: hygiene

#1350 PR1348: some minor updates and suggestions for instructions
  test/grafana/README.md
  test/grafana/datasource.sh
Labels: monitoring

#1307 docs: gRPC services and data companion pruning services
  docs/data-companion/README.md
  docs/data-companion/grpc.md
  docs/data-companion/intro.md
  docs/data-companion/pruning.md
Labels: documentation, grpc, P:storage-optimization

#1324 Add genesis_hash flag check on node startup
  .changelog/unreleased/breaking-changes/1324-load-state-from-gen-file-api.md
  .changelog/unreleased/improvements/1324-cli-genesis-hash-checked-on-load.md
  cmd/cometbft/commands/run_node.go
  config/config.go
  config/toml.go
  node/node.go
  node/node_test.go
  node/setup.go
Labels: P:storage-optimization

#1327 gRPC for Tx and Block indexer pruning
  .changelog/unreleased/features/1327-grpc-pruning-indexer.md
  proto/tendermint/services/pruning/v1/pruning.pb.go
  proto/tendermint/services/pruning/v1/pruning.proto
  proto/tendermint/services/pruning/v1/service.pb.go
  proto/tendermint/services/pruning/v1/service.proto
  rpc/grpc/client/privileged/pruning_service.go
  rpc/grpc/server/services/pruningservice/service.go
  test/e2e/tests/grpc_test.go
Labels: storage, grpc, P:storage-optimization

#1384 Max byte check
  docs/guides/go-built-in.md
  docs/guides/go.md
Labels: automerge, backport-to-v0.38.x

#1385 Update to string
  rpc/openapi/openapi.yaml
Labels: automerge, backport-to-v0.37.x, backport-to-v0.38.x

#1379 mempool: Remove unused peerID-related constants
  mempool/mempool.go
  mempool/reactor_test.go
Labels: mempool, hygiene

#1351 Bump Go version used in `v0.34.x` to v1.20
  .changelog/unreleased/build/1351-bump-go-120.md
  .github/workflows/check-generated.yml
  .github/workflows/coverage.yml
  .github/workflows/e2e-manual.yml
  .github/workflows/e2e-nightly-34x.yml
  .github/workflows/e2e.yml
  .github/workflows/fuzz-nightly.yml
  .github/workflows/govulncheck.yml
  .github/workflows/lint.yml
  .github/workflows/pre-release.yml
  .github/workflows/release-version.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .golangci.yml
  DOCKER/Dockerfile
  Makefile
  README.md
  UPGRADING.md
  docs/guides/upgrading-from-tm.md
  go.mod
  go.sum
  p2p/conn/connection.go
  test/docker/Dockerfile
  test/e2e/docker/Dockerfile
Labels: chore

#1383 docs: Fix broken links and remove invalid content on v0.38 docs
  docs/README.md
  docs/app-dev/app-architecture.md
  docs/app-dev/getting-started.md
  docs/app-dev/indexing-transactions.md
  docs/core/running-in-production.md
  docs/core/subscription.md
  docs/core/using-cometbft.md
  docs/introduction/README.md
  docs/networks/docker-compose.md
  docs/qa/CometBFT-QA-37.md
  docs/qa/CometBFT-QA-38.md
  docs/qa/TMCore-QA-37.md
  docs/qa/method.md
  docs/tools/debugging.md
  spec/README.md
  spec/abci/abci++_app_requirements.md
  spec/abci/abci++_basic_concepts.md
  spec/abci/abci++_comet_expected_behavior.md
  spec/abci/abci++_methods.md
  spec/consensus/README.md
  spec/consensus/consensus-paper/README.md
  spec/consensus/evidence.md
  spec/consensus/proposer-based-timestamp/pbts-algorithm_001_draft.md
  spec/consensus/proposer-based-timestamp/pbts-sysmodel_001_draft.md
  spec/consensus/proposer-based-timestamp/pbts_001_draft.md
  spec/consensus/proposer-selection.md
  spec/consensus/signing.md
  spec/consensus/wal.md
  spec/core/data_structures.md
  spec/light-client/accountability/README.md
  spec/p2p/implementation/README.md
  spec/p2p/legacy-docs/README.md
  spec/p2p/legacy-docs/config.md
  spec/p2p/legacy-docs/connection.md
  spec/p2p/legacy-docs/messages/consensus.md
  spec/p2p/legacy-docs/messages/state-sync.md
  spec/p2p/legacy-docs/node.md
  spec/p2p/legacy-docs/peer.md
  spec/p2p/reactor-api/README.md
  spec/p2p/reactor-api/p2p-api.md
  spec/p2p/reactor-api/reactor.md
Labels: documentation

#1405 doc: improve documentation of BlockParams.MaxBytes
  spec/abci/abci++_app_requirements.md
Labels: documentation, backport-to-v0.37.x, backport-to-v0.38.x

#1184 rpc: Improve abci_query parameter documentation
  docs/guides/go-built-in.md
  docs/guides/go.md
  rpc/openapi/openapi.yaml
  spec/abci/abci++_methods.md
  spec/rpc/README.md
Labels: documentation

#1391 RFC: Allowing Non-Determinism in `ProcessProposal`
  docs/rfc/README.md
  docs/rfc/rfc-105-non-det-process-proposal.md
Labels: documentation, rfc
