Repository cometbft/cometbft, pull requests merged in 2023-11, with the labels that each got.

#1512 mempool: Add metric size of pool in bytes
  .changelog/unreleased/features/1512-metric-mempool-size-bytes.md
  mempool/clist_mempool.go
  mempool/metrics.gen.go
  mempool/metrics.go
Labels: mempool, metrics, backport-to-v0.34.x, backport-to-v0.37.x, stale, backport-to-v0.38.x

#1578 chore: Consolidate changelog improvements section
  .changelog/unreleased/improvements/1096-config-pruner.md
  .changelog/unreleased/improvements/1096-node-pruner.md
  .changelog/unreleased/improvements/1096-state-abcires-pruning.md
  .changelog/unreleased/improvements/1096-state-background-pruning.md
Labels: chore

#930 Implementation of ADR-108
  go.mod
  go.sum
  test/e2e/Makefile
  test/e2e/app/app.go
  test/e2e/app/log_abci.go
  test/e2e/app/log_abci_test.go
  test/e2e/networks/ci.toml
  test/e2e/node/config.go
  test/e2e/pkg/grammar/README.md
  test/e2e/pkg/grammar/checker.go
  test/e2e/pkg/grammar/checker_test.go
  test/e2e/pkg/grammar/clean-start/abci_grammar_clean_start.md
  test/e2e/pkg/grammar/clean-start/grammar-auto/lexer/lexer.go
  test/e2e/pkg/grammar/clean-start/grammar-auto/parser/bsr/bsr.go
  test/e2e/pkg/grammar/clean-start/grammar-auto/parser/parser.go
  test/e2e/pkg/grammar/clean-start/grammar-auto/parser/slot/slot.go
  test/e2e/pkg/grammar/clean-start/grammar-auto/parser/symbols/symbols.go
  test/e2e/pkg/grammar/clean-start/grammar-auto/sppf/sppf.go
  test/e2e/pkg/grammar/clean-start/grammar-auto/token/token.go
  test/e2e/pkg/grammar/recovery/abci_grammar_recovery.md
  test/e2e/pkg/grammar/recovery/grammar-auto/lexer/lexer.go
  test/e2e/pkg/grammar/recovery/grammar-auto/parser/bsr/bsr.go
  test/e2e/pkg/grammar/recovery/grammar-auto/parser/parser.go
  test/e2e/pkg/grammar/recovery/grammar-auto/parser/slot/slot.go
  test/e2e/pkg/grammar/recovery/grammar-auto/parser/symbols/symbols.go
  test/e2e/pkg/grammar/recovery/grammar-auto/sppf/sppf.go
  test/e2e/pkg/grammar/recovery/grammar-auto/token/token.go
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
  test/e2e/tests/abci_test.go
  test/e2e/tests/e2e_test.go
Labels: wip

#1518 Reduce the default MaxBytes to 4mb and increase MaxGas to 10 million
  .changelog/unreleased/improvements/1518-reduce-default-maxbytes_increase_maxgas
  docs/core/using-cometbft.md
  types/params.go
Labels: consensus

#1580 e2e: Allow disabling the PEX reactor on all nodes in the testnet
  .changelog/unreleased/improvements/1579-e2e-disable-pex-reactor.md
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
Labels: e2e

#1558 Experimental - Reduce # of connections effectively used to gossip transactions out
  .changelog/unreleased/improvements/1558-experimental-gossip-limiting.md
  config/config.go
  config/toml.go
  mempool/metrics.gen.go
  mempool/metrics.go
  mempool/reactor.go
  mempool/reactor_test.go
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
Labels: mempool, P:bandwidth-optimization, experimental-backport

#1555 Update proto file references to follow renaming/versioning
  proto/tendermint/services/block/v1/block.proto
  proto/tendermint/services/block/v1/block_service.proto
  proto/tendermint/services/block_results/v1/block_results.proto
  proto/tendermint/services/block_results/v1/block_results_service.proto
  proto/tendermint/services/version/v1/version.proto
  proto/tendermint/services/version/v1/version_service.proto
  spec/abci/README.md
  spec/abci/abci++_basic_concepts.md
  spec/abci/abci++_client_server.md
  spec/abci/abci++_comet_expected_behavior.md
Labels: documentation, protobuf

#1557 Make `LoadBlock` also return block metadata
  .changelog/unreleased/breaking-changes/1556-return-meta-with-load-block.md
  blocksync/reactor.go
  blocksync/reactor_test.go
  cmd/cometbft/commands/reindex_event.go
  cmd/cometbft/commands/reindex_event_test.go
  consensus/replay.go
  consensus/replay_test.go
  inspect/inspect_test.go
  rpc/core/blocks.go
  rpc/core/tx.go
  rpc/grpc/server/services/blockservice/service.go
  state/mocks/block_store.go
  state/services.go
  store/store.go
  store/store_test.go
  test/loadtime/report/report.go
  test/loadtime/report/report_test.go
Labels: storage, P:operator-experience

#1584 mempool: Limit gossip connections to persistent and non-persistent peers (experimental)
  .changelog/unreleased/improvements/1558-experimental-gossip-limiting.md
  config/config.go
  config/toml.go
  mempool/reactor.go
  mempool/reactor_test.go
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
Labels: mempool, experimental-backport

#1590 Updates grpc and net dependencies to avoid https://pkg.go.dev/vuln/GO-2023-2153 and https://pkg.go.dev/vuln/GO-2023-2102
  go.mod
  go.sum
Labels: dependencies, ci

#1589 Updates grpc and net dependencies to avoid https://pkg.go.dev/vuln/GO…
  go.mod
  go.sum
Labels: dependencies, ci

#1164 RFC 107: Internal signalling using event observers
  docs/rfc/README.md
  docs/rfc/rfc-107-event-observer.md
Labels: documentation, wip, P:tech-debt, rfc

#1565 ADR 110: Remote mempool
  docs/architecture/README.md
  docs/architecture/adr-110-remote-mempool.md
Labels: mempool, wip, adr

#1606 chore: ADR 109: go mod tidy
  go.mod
  test/e2e/app/go.mod
  test/e2e/go.mod
  test/loadtime/go.mod
Labels: chore

#1592 Backports #1558 and #1584 to 0.38.x
  .changelog/unreleased/improvements/1558-experimental-gossip-limiting.md
  config/config.go
  config/toml.go
  mempool/clist_mempool_test.go
  mempool/metrics.gen.go
  mempool/metrics.go
  mempool/reactor.go
  mempool/reactor_test.go
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
Labels: backport-to-v0.37.x, P:bandwidth-optimization

#1609 deps: upgrade gogoproto to 1.4.11
  go.mod
  go.sum
Labels: dependencies

#1603 docs: various improvements
  docs/guides/go-built-in.md
  docs/guides/go.md
  docs/guides/install.md
  docs/introduction/README.md
Labels: documentation, backport-to-v0.38.x

#1611 Backports #1558 and #1584 to 0.37.x (#1592)
  .changelog/unreleased/improvements/1558-experimental-gossip-limiting.md
  abci/example/kvstore/helpers.go
  config/config.go
  config/toml.go
  mempool/metrics.gen.go
  mempool/metrics.go
  mempool/v0/clist_mempool_test.go
  mempool/v0/reactor.go
  mempool/v0/reactor_test.go
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
Labels: P:bandwidth-optimization

#1627 Fixes back port of test in 0.38
  mempool/reactor_test.go
Labels: e2e

#1629 Fixes back port of test in 0.37
  mempool/v0/reactor_test.go
Labels: e2e

#1616 pruning:do not attempt to prune state if no blocks are pruned
  .changelog/unreleased/bug-fixes/1616-pruning-dont-prune-state-when-no-blocks-pruned.md
  internal/state/export_test.go
  internal/state/pruner.go
  internal/state/pruner_test.go
Labels: experimental-backport

#1626 Update SECURITY.md
  SECURITY.md
Labels: documentation, backport-to-v0.34.x, backport-to-v0.37.x, security, backport-to-v0.38.x

#1624 v0.38.x: Bump Go version to v1.21
  .github/workflows/build.yml
  .github/workflows/check-generated.yml
  .github/workflows/e2e-manual-multiversion.yml
  .github/workflows/e2e-manual.yml
  .github/workflows/e2e-nightly-37x.yml
  .github/workflows/e2e-nightly-main.yml
  .github/workflows/e2e.yml
  .github/workflows/fuzz-nightly.yml
  .github/workflows/govulncheck.yml
  .github/workflows/lint.yml
  .github/workflows/pre-release.yml
  .github/workflows/release-version.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  DOCKER/Dockerfile
  go.mod
  go.sum
  test/e2e/docker/Dockerfile
  test/fuzz/README.md
  test/fuzz/tests/mempool_test.go
  test/fuzz/tests/p2p_secretconnection_test.go
  test/fuzz/tests/rpc_jsonrpc_server_test.go
Labels: chore

#1625 v0.37.x: Bump Go version to v1.21
  .github/workflows/build.yml
  .github/workflows/check-generated.yml
  .github/workflows/e2e-long-37x.yml
  .github/workflows/e2e-manual-multiversion.yml
  .github/workflows/e2e-manual.yml
  .github/workflows/e2e-nightly-37x.yml
  .github/workflows/e2e-nightly-main.yml
  .github/workflows/e2e.yml
  .github/workflows/fuzz-nightly.yml
  .github/workflows/govulncheck.yml
  .github/workflows/lint.yml
  .github/workflows/pre-release.yml
  .github/workflows/release-version.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  DOCKER/Dockerfile
  go.mod
  go.sum
  test/e2e/docker/Dockerfile
Labels: chore

#1632 pruning:do not attempt to prune state if no blocks are pruned (#1616)
  .changelog/unreleased/bug-fixes/1616-pruning-dont-prune-state-when-no-blocks-pruned.md
  state/export_test.go
  state/pruner.go
  state/pruner_test.go
Labels: bug

#1631 Comment that experimental mempool only applies to v0
  .changelog/unreleased/improvements/1558-experimental-gossip-limiting.md
  config/config.go
  config/toml.go
Labels: mempool

#1630 experimental mempool: Backport #1558 and #1584 to 0.34.x
  .changelog/unreleased/improvements/1558-experimental-gossip-limiting.md
  abci/example/kvstore/helpers.go
  config/config.go
  config/toml.go
  mempool/metrics.go
  mempool/v0/clist_mempool_test.go
  mempool/v0/reactor.go
  mempool/v0/reactor_test.go
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
Labels: mempool, experimental-backport

#1642 mempool: Add missing gauge constructor for `size_bytes` metric
  mempool/metrics.go
Labels: bug

#1641 Release v0.34.30
  .changelog/v0.34.30/build/1351-bump-go-120.md
  .changelog/v0.34.30/features/1512-metric-mempool-size-bytes.md
  .changelog/v0.34.30/improvements/1210-close-evidence-db.md
  .changelog/v0.34.30/improvements/1558-experimental-gossip-limiting.md
  .changelog/v0.34.30/improvements/857-make-handshake-cancelable.md
  .changelog/v0.34.30/summary.md
  CHANGELOG.md
  version/version.go
Labels: release

#1640 Release v0.37.3
  .changelog/v0.37.3/breaking-changes/1113-rm-upnp.md
  .changelog/v0.37.3/bug-fixes/1529-indexer-respect-height-params-on-query.md
  .changelog/v0.37.3/features/1057-bootstrap-state-api.md
  .changelog/v0.37.3/features/1512-metric-mempool-size-bytes.md
  .changelog/v0.37.3/improvements/1210-close-evidence-db.md
  .changelog/v0.37.3/improvements/1558-experimental-gossip-limiting.md
  .changelog/v0.37.3/improvements/475-upgrade-go-schnorrkel.md
  .changelog/v0.37.3/improvements/857-make-handshake-cancelable.md
  .changelog/v0.37.3/summary.md
  CHANGELOG.md
  version/version.go
Labels: release

#1639 Release v0.38.1
  .changelog/v0.38.1/bug-fixes/1529-indexer-respect-height-params-on-query.md
  .changelog/v0.38.1/features/1512-metric-mempool-size-bytes.md
  .changelog/v0.38.1/improvements/1558-experimental-gossip-limiting.md
  .changelog/v0.38.1/summary.md
  CHANGELOG.md
  version/version.go
Labels: release

#1644 Update changelog on `main` with new releases
  .changelog/v0.34.30/build/1351-bump-go-120.md
  .changelog/v0.34.30/features/1512-metric-mempool-size-bytes.md
  .changelog/v0.34.30/improvements/1210-close-evidence-db.md
  .changelog/v0.34.30/improvements/1558-experimental-gossip-limiting.md
  .changelog/v0.34.30/improvements/857-make-handshake-cancelable.md
  .changelog/v0.34.30/summary.md
  .changelog/v0.37.3/breaking-changes/1113-rm-upnp.md
  .changelog/v0.37.3/bug-fixes/1529-indexer-respect-height-params-on-query.md
  .changelog/v0.37.3/features/1057-bootstrap-state-api.md
  .changelog/v0.37.3/features/1512-metric-mempool-size-bytes.md
  .changelog/v0.37.3/improvements/1210-close-evidence-db.md
  .changelog/v0.37.3/improvements/1558-experimental-gossip-limiting.md
  .changelog/v0.37.3/improvements/475-upgrade-go-schnorrkel.md
  .changelog/v0.37.3/improvements/857-make-handshake-cancelable.md
  .changelog/v0.37.3/summary.md
  .changelog/v0.38.1/bug-fixes/1529-indexer-respect-height-params-on-query.md
  .changelog/v0.38.1/features/1512-metric-mempool-size-bytes.md
  .changelog/v0.38.1/improvements/1558-experimental-gossip-limiting.md
  .changelog/v0.38.1/summary.md
  CHANGELOG.md
Labels: documentation, chore

#1648 proto: Update README
  proto/README.md
Labels: documentation, protobuf, backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x

#1645 proto: Prepare for publishing v0.34.x protos to Buf registry
  proto/buf.lock
  proto/buf.yaml
Labels: protobuf

#1646 proto: Prepare for publishing v0.37.x protos to Buf registry
  proto/buf.lock
  proto/buf.yaml
Labels: protobuf

#1647 proto: Prepare for publishing v0.38.x protos to Buf registry
  proto/buf.lock
  proto/buf.yaml
Labels: protobuf

#1585 ADR 111: `nop` Mempool
  docs/architecture/README.md
  docs/architecture/adr-111-nop-mempool.md
Labels: mempool, adr

#1655 ci: Fix v0.34 nightly build
  .github/workflows/e2e-nightly-34x.yml
Labels: ci

#1673 feature/proto-upgrade: Fix generated mock code
  internal/state/mocks/store.go
Labels: chore

#1643 mempool: add `nop` mempool
  .changelog/unreleased/features/1643-nop-mempool.md
  config/config.go
  config/config_test.go
  config/toml.go
  docs/architecture/README.md
  docs/architecture/adr-111-nop-mempool.md
  docs/core/configuration.md
  docs/core/mempool.md
  mempool/nop_mempool.go
  mempool/nop_mempool_test.go
  node/node.go
  node/setup.go
Labels: enhancement, mempool, backport-to-v0.37.x, backport-to-v0.38.x

#1683 docs: various small improvements (part 2)
  docs/app-dev/abci-cli.md
  docs/app-dev/indexing-transactions.md
  docs/core/block-structure.md
  docs/core/state-sync.md
  docs/core/using-cometbft.md
Labels: documentation, backport-to-v0.37.x, backport-to-v0.38.x

#1654 Do not block indefinitely on the semaphore
  config/config.go
  config/toml.go
  mempool/reactor.go
  test/e2e/pkg/manifest.go
Labels: backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x

#1628 Adds tests that check for FIFO ordering being broken by gossip
  mempool/clist_mempool.go
  mempool/reactor_test.go
  p2p/test_util.go
Labels: mempool, backport-to-v0.37.x, e2e, backport-to-v0.38.x

#1511 qa: Add parameter to loadtime/report for displaying results in one line
  test/loadtime/cmd/report/main.go
Labels: qa

#1698 Release v0.34.31
  .changelog/v0.34.31/bug-fixes/1654-semaphore-wait.md
  .changelog/v0.34.31/summary.md
  CHANGELOG.md
  version/version.go
Labels: release

#1699 Release v0.37.4
  .changelog/v0.37.4/bug-fixes/1654-semaphore-wait.md
  .changelog/v0.37.4/features/1643-nop-mempool.md
  .changelog/v0.37.4/summary.md
  CHANGELOG.md
  version/version.go
Labels: release

#1700 Release v0.38.2
  .changelog/v0.38.2/bug-fixes/1654-semaphore-wait.md
  .changelog/v0.38.2/features/1643-nop-mempool.md
  .changelog/v0.38.2/summary.md
  CHANGELOG.md
  version/version.go
Labels: release

#1701 chore: Update CHANGELOG.md
  .changelog/v0.34.31/bug-fixes/1654-semaphore-wait.md
  .changelog/v0.34.31/summary.md
  .changelog/v0.37.4/bug-fixes/1654-semaphore-wait.md
  .changelog/v0.37.4/features/1643-nop-mempool.md
  .changelog/v0.37.4/summary.md
  .changelog/v0.38.2/bug-fixes/1654-semaphore-wait.md
  .changelog/v0.38.2/features/1643-nop-mempool.md
  .changelog/v0.38.2/summary.md
  CHANGELOG.md
Labels: chore

#1703 chore(proto): add missing docs
  proto/buf.yaml
  proto/cometbft/abci/v1/service.proto
  proto/cometbft/abci/v1/types.proto
  proto/cometbft/abci/v1beta1/types.proto
  proto/cometbft/abci/v1beta2/types.proto
  proto/cometbft/abci/v1beta3/types.proto
  proto/cometbft/blocksync/v1/types.proto
  proto/cometbft/blocksync/v1beta1/types.proto
  proto/cometbft/consensus/v1/types.proto
  proto/cometbft/consensus/v1/wal.proto
  proto/cometbft/consensus/v1beta1/types.proto
  proto/cometbft/consensus/v1beta1/wal.proto
  proto/cometbft/crypto/v1/keys.proto
  proto/cometbft/crypto/v1/proof.proto
  proto/cometbft/libs/bits/v1/types.proto
  proto/cometbft/mempool/v1/types.proto
  proto/cometbft/p2p/v1/conn.proto
  proto/cometbft/p2p/v1/pex.proto
  proto/cometbft/p2p/v1/types.proto
  proto/cometbft/privval/v1/types.proto
  proto/cometbft/privval/v1beta1/types.proto
  proto/cometbft/rpc/grpc/v1beta1/types.proto
  proto/cometbft/rpc/grpc/v1beta2/types.proto
  proto/cometbft/rpc/grpc/v1beta3/types.proto
  proto/cometbft/services/block/v1/block.proto
  proto/cometbft/services/block_results/v1/block_results.proto
  proto/cometbft/services/pruning/v1/pruning.proto
  proto/cometbft/services/version/v1/version.proto
  proto/cometbft/state/v1/types.proto
  proto/cometbft/state/v1beta1/types.proto
  proto/cometbft/state/v1beta2/types.proto
  proto/cometbft/state/v1beta3/types.proto
  proto/cometbft/statesync/v1/types.proto
  proto/cometbft/store/v1/types.proto
  proto/cometbft/types/v1/block.proto
  proto/cometbft/types/v1/canonical.proto
  proto/cometbft/types/v1/events.proto
  proto/cometbft/types/v1/evidence.proto
  proto/cometbft/types/v1/types.proto
  proto/cometbft/types/v1/validator.proto
  proto/cometbft/types/v1beta1/block.proto
  proto/cometbft/types/v1beta1/canonical.proto
  proto/cometbft/types/v1beta1/events.proto
  proto/cometbft/types/v1beta1/evidence.proto
  proto/cometbft/types/v1beta1/types.proto
  proto/cometbft/types/v1beta1/validator.proto
  proto/cometbft/types/v1beta2/params.proto
  proto/tendermint/services/pruning/v1/pruning.proto
  proto/tendermint/services/pruning/v1/service.proto
  proto/tendermint/types/types.proto
  proto/tendermint/types/validator.proto
Labels: documentation

#1709 feature/proto-upgrade: Last-minute fixes
  .github/workflows/check-generated.yml
  Makefile
  api/cometbft/abci/v1/service.pb.go
  api/cometbft/abci/v1/types.pb.go
  api/cometbft/abci/v1beta1/types.pb.go
  api/cometbft/abci/v1beta2/types.pb.go
  api/cometbft/abci/v1beta3/types.pb.go
  api/cometbft/blocksync/v1/types.pb.go
  api/cometbft/blocksync/v1beta1/types.pb.go
  api/cometbft/consensus/v1/types.pb.go
  api/cometbft/consensus/v1/wal.pb.go
  api/cometbft/consensus/v1beta1/types.pb.go
  api/cometbft/consensus/v1beta1/wal.pb.go
  api/cometbft/crypto/v1/keys.pb.go
  api/cometbft/crypto/v1/proof.pb.go
  api/cometbft/libs/bits/v1/types.pb.go
  api/cometbft/mempool/v1/types.pb.go
  api/cometbft/p2p/v1/conn.pb.go
  api/cometbft/p2p/v1/pex.pb.go
  api/cometbft/p2p/v1/types.pb.go
  api/cometbft/privval/v1/types.pb.go
  api/cometbft/privval/v1beta1/types.pb.go
  api/cometbft/rpc/grpc/v1beta1/types.pb.go
  api/cometbft/rpc/grpc/v1beta2/types.pb.go
  api/cometbft/rpc/grpc/v1beta3/types.pb.go
  api/cometbft/services/block/v1/block.pb.go
  api/cometbft/services/block_results/v1/block_results.pb.go
  api/cometbft/services/pruning/v1/pruning.pb.go
  api/cometbft/services/version/v1/version.pb.go
  api/cometbft/state/v1/types.pb.go
  api/cometbft/state/v1beta1/types.pb.go
  api/cometbft/state/v1beta2/types.pb.go
  api/cometbft/state/v1beta3/types.pb.go
  api/cometbft/statesync/v1/types.pb.go
  api/cometbft/store/v1/types.pb.go
  api/cometbft/types/v1/block.pb.go
  api/cometbft/types/v1/canonical.pb.go
  api/cometbft/types/v1/events.pb.go
  api/cometbft/types/v1/evidence.pb.go
  api/cometbft/types/v1/types.pb.go
  api/cometbft/types/v1/validator.pb.go
  api/cometbft/types/v1beta1/block.pb.go
  api/cometbft/types/v1beta1/canonical.pb.go
  api/cometbft/types/v1beta1/events.pb.go
  api/cometbft/types/v1beta1/evidence.pb.go
  api/cometbft/types/v1beta1/types.pb.go
  api/cometbft/types/v1beta1/validator.pb.go
Labels: protobuf

#1560 e2e: Support emulated latencies between docker images
  .changelog/unreleased/improvements/1560-e2e-latency-emulation.md
  test/e2e/docker/Dockerfile
  test/e2e/pkg/infra/digitalocean/digitalocean.go
  test/e2e/pkg/infra/docker/docker.go
  test/e2e/pkg/infra/provider.go
  test/e2e/pkg/latency/aws-latencies.csv
  test/e2e/pkg/latency/latency-setter.py
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/start.go
Labels: enhancement, e2e
