Repository cometbft/cometbft, pull requests merged in 2023-12, with the labels that each got.

#1715 types: validate Validator#Address field
  .changelog/unreleased/improvements/1715-validate-validator-address
  internal/state/store_test.go
  internal/store/store_test.go
  types/validator.go
  types/validator_set_test.go
  types/validator_test.go
Labels: backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#1724 Enable Mergify backports for `v1.x` branch
  .github/mergify.yml
Labels: automation

#1725 deps: Bump cometbft-db to v0.9.0
  .changelog/unreleased/dependencies/1725-cometbft-db.md
  go.mod
  go.sum
  test/e2e/docker/Dockerfile
  test/e2e/docker/Dockerfile.debug
Labels: dependencies, backport-to-v1.x

#1737 deps: Bump cometbft-db to v0.9.1
  go.mod
  go.sum
  test/e2e/docker/Dockerfile
  test/e2e/docker/Dockerfile.debug
Labels: dependencies, ci, docker, backport-to-v1.x

#1741 chore: Fix changelog entry (`v1.x`)
  .changelog/v1.0.0-alpha.1/improvements/1715-validate-validator-address.md
  CHANGELOG.md
Labels: documentation, chore

#1730 fix: increase abci socket message size limit to 2GB
  .changelog/unreleased/improvements/1730-increase-abci-socket-message-size-limit
  abci/types/messages.go
Labels: backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#1743 proto: make comment in README more Markdowny
  proto/README.md
Labels: documentation, protobuf, backport-to-v1.x

#1687 fix: Txs Validate
  types/tx.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x

#1712 Add test missing in #1687
  .changelog/unreleased/bug-fixes/1687-consensus-fix-block-validation.md
  abci/example/kvstore/kvstore.go
  internal/state/execution_test.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#1708 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#1763 changelog: remove already released entry
  .changelog/unreleased/improvements/1715-validate-validator-address.md
Labels: automerge

#1756 [e2e] Fixes prepareProposal not to return oversized set of transactions
  test/e2e/app/app.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#1781 chore(docs): small improvements
  docs/app-dev/abci-cli.md
  docs/app-dev/app-architecture.md
  docs/app-dev/getting-started.md
  docs/app-dev/indexing-transactions.md
  docs/core/metrics.md
  docs/core/validators.md
  docs/data-companion/README.md
  docs/guides/install.md
  docs/guides/quick-start.md
  docs/qa/README.md
  docs/tools/README.md
Labels: backport-to-v0.38.x, backport-to-v1.x

#1804 chore(spec): specify which fields must be deterministic
  proto/cometbft/abci/v1/types.proto
  spec/abci/abci++_basic_concepts.md
  spec/abci/abci++_methods.md
Labels: backport-to-v0.38.x, backport-to-v1.x

#1806 Introduce `countAllSignatures` in `VerifyCommitLight` & `VerifyCommitLightTrusting`
  blocksync/reactor.go
  evidence/pool.go
  evidence/verify.go
  test/e2e/app/app.go
  test/e2e/runner/evidence.go
  types/validator_set.go
  types/validator_set_test.go
Labels: bug

#1808 Small improvements in #1806 not present in #1750
  types/validation.go
  types/validation_test.go
Labels: bug, backport-to-v0.38.x, backport-to-v1.x

#1807 Add changelog for #1749
  .changelog/unreleased/bug-fixes/1749-light-client-attack-verify-all-sigs.md
Labels: bug, backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#1815 Introduce `countAllSignatures` in `VerifyCommitLight` & `VerifyCommitLightTrusting` (backport of #1806)
  blockchain/v0/reactor.go
  blockchain/v1/reactor.go
  blockchain/v2/processor_context.go
  evidence/pool.go
  evidence/verify.go
  test/e2e/app/app.go
  types/validator_set.go
  types/validator_set_test.go
Labels: bug

#1587 e2e: Implement latency emulation for DigitalOcean
  .changelog/unreleased/improvements/1559-e2e-latency-emulation.md
  test/e2e/pkg/infra/digitalocean/digitalocean.go
  test/e2e/pkg/infra/docker/docker.go
  test/e2e/pkg/infra/latencies.go
  test/e2e/pkg/infra/provider.go
Labels: enhancement, qa, e2e

#1824 add GH workflow for linting code using codespell
  .codespellrc
  .github/workflows/codespell.yml
  .github/workflows/ignore-words.txt
  Makefile
  p2p/switch.go
  rpc/client/rpc_test.go
  spec/light-client/detection/draft-functions.md
Labels: ci

#1828 v1.x: Improve upgrading guidelines
  .changelog/v1.0.0-alpha.1/breaking-changes/736+-proto-renaming.md
  CHANGELOG.md
  UPGRADING.md
Labels: documentation, protobuf

#1798 chore(docs): explain the effect of `timeout_propose`
  docs/core/configuration.md
  test/e2e/pkg/infra/digitalocean/digitalocean.go
Labels: backport-to-v0.38.x, backport-to-v1.x

#1859 Updates go crypto package to v0.17.0
  go.mod
  go.sum
Labels: security, chore, go

#1855 Adds checks for nil keys and signatures
  .changelog/unreleased/bug-fixes/1825-false-on-nil-key.md
  crypto/batch/batch.go
  types/validation.go
  types/validator_set_test.go
Labels: crypto, e2e

#1856 The store DB and the companion `BlockStore` struct are sometimes out of sync
  internal/store/store.go
Labels: bug, backport-to-v0.38.x, backport-to-v1.x

#1858 Allow blocksync to not verify all signatures
  internal/blocksync/reactor.go
Labels: backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#1874 docs: Fix Discord links in README
  README.md
Labels: documentation, backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x
