Repository cometbft/cometbft, pull requests merged in 2023-07, with the labels that each got.

#1118 ci: Trigger workflows on merge group
  .github/workflows/build.yml
  .github/workflows/check-generated.yml
  .github/workflows/codeql.yml
  .github/workflows/e2e.yml
  .github/workflows/govulncheck.yml
  .github/workflows/lint.yml
  .github/workflows/proto-lint.yml
  .github/workflows/tests.yml
Labels: ci

#1109 Revert "config: add bootstrap peers (#9680)"
  UPGRADING.md
  cmd/cometbft/commands/run_node.go
  config/config.go
  config/toml.go
  docs/core/configuration.md
  node/node.go
  spec/p2p/legacy-docs/config.md
Labels: config, p2p, backport-to-v0.38.x

#1120 node: Revert removal of public reactor accessors
  .changelog/unreleased/breaking-changes/1120-node-api-cleanup.md
  node/node.go
  node/setup.go
  p2p/switch.go
Labels: backport-to-v0.38.x, P:consensus-engine-devs

#1123 ci: Disable CodeQL check in merge queues
  .github/workflows/codeql.yml
Labels: ci

#1124 Release v0.38.0-rc3
  .changelog/unreleased/features/9680-config-introduce-bootstrappeers.md
  CHANGELOG.md
  version/version.go
Labels: release

#1114 p2p: Remove UPnP functionality
  .changelog/unreleased/breaking-changes/1113-rm-upnp.md
  cmd/cometbft/commands/probe_upnp.go
  cmd/cometbft/commands/run_node.go
  cmd/cometbft/main.go
  config/config.go
  config/toml.go
  docs/core/configuration.md
  docs/core/how-to-read-logs.md
  p2p/upnp/probe.go
  p2p/upnp/upnp.go
  spec/p2p/implementation/configuration.md
  spec/p2p/implementation/types.md
Labels: backport-to-v0.37.x, backport-to-v0.38.x

#1110 ADR 107: Rename proto versions to pre-v1 betas
  docs/architecture/README.md
  docs/architecture/adr-107-betaize-proto-versions.md
Labels: protobuf, P:integrator-experience

#1092 RFC 104: Internal messaging using the actor model
  docs/rfc/README.md
  docs/rfc/rfc-104-actor-model.md
Labels: documentation, wip, P:tech-debt, rfc

#997 spec: Add mempool specification in English and Quint
  spec/mempool/mempool.md
  spec/mempool/quint/Consensus.qnt
  spec/mempool/quint/Ledger.qnt
  spec/mempool/quint/Mempool.qnt
  spec/mempool/quint/Spells.qnt
  spec/mempool/quint/System.qnt
  spec/mempool/quint/test.sh
Labels: mempool, spec

#1145 proxy: Rename "unsynchronized" to "connection-synchronized" local client creator
  .changelog/unreleased/features/9830-proxy-introduce-newconnsynclocalclientcreator.md
  proxy/client.go
  test/e2e/generator/generate.go
  test/e2e/node/config.go
  test/e2e/node/main.go
  test/e2e/pkg/infra/docker/docker.go
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
Labels: abci, backport-to-v0.38.x

#1010 mempool: Keep track of senders in reactor instead of implementation
  .changelog/unreleased/breaking-changes/1010-mempool-interface.md
  UPGRADING.md
  consensus/mempool_test.go
  consensus/reactor_test.go
  consensus/replay_stubs.go
  consensus/replay_test.go
  mempool/bench_test.go
  mempool/cache_test.go
  mempool/clist_mempool.go
  mempool/clist_mempool_test.go
  mempool/mempool.go
  mempool/mempoolTx.go
  mempool/mocks/mempool.go
  mempool/reactor.go
  mempool/reactor_test.go
  mempool/tx.go
  node/node_test.go
  rpc/client/rpc_test.go
  rpc/core/mempool.go
  test/fuzz/mempool/checktx.go
  test/fuzz/tests/mempool_test.go
Labels: mempool

#1170 cmd: Remove `replay` and `replay-console` subcommands
  .changelog/unreleased/breaking-changes/1170-rm-replay-cmds.md
  UPGRADING.md
  cmd/cometbft/commands/replay.go
  cmd/cometbft/main.go
  consensus/replay_file.go
Labels: breaking, P:tech-debt

#1182 ci: Remove Mergify automerge
  .github/mergify.yml
Labels: ci
