Repository cometbft/cometbft, pull requests merged in 2023-08, with the labels that each got.

#1142 Add gRPC block service
  .changelog/unreleased/features/1094-grpc-block-service-cfg.md
  .changelog/unreleased/features/1094-grpc-block-service.md
  config/config.go
  config/toml.go
  docs/core/configuration.md
  internal/rpctrace/rpctrace.go
  node/node.go
  proto/buf.yaml
  proto/tendermint/services/block/v1/block.pb.go
  proto/tendermint/services/block/v1/block.proto
  proto/tendermint/services/block/v1/block_service.pb.go
  proto/tendermint/services/block/v1/block_service.proto
  rpc/grpc/client/block_service.go
  rpc/grpc/client/client.go
  rpc/grpc/server/server.go
  rpc/grpc/server/services/blockservice/service.go
  test/e2e/tests/grpc_test.go
Labels: grpc

#1187 Merge `main` into `feature/adr101-pull-companion`
  .changelog/unreleased/breaking-changes/1170-rm-replay-cmds.md
  .github/mergify.yml
  UPGRADING.md
  cmd/cometbft/commands/replay.go
  cmd/cometbft/main.go
  consensus/replay_file.go
  go.mod
  go.sum
Labels: chore

#1186 blocksync: export errors
  blocksync/errors.go
  blocksync/msgs.go
  blocksync/reactor.go
Labels: P:tech-debt, backport-to-v0.38.x, P:consensus-engine-devs

#1168 Add BlockResults gRPC service
  .changelog/unreleased/features/1095-grpc-block-results-service-cfg.md
  .changelog/unreleased/features/1095-grpc-block-results-service.md
  config/config.go
  config/toml.go
  node/node.go
  proto/tendermint/abci/types.proto
  proto/tendermint/consensus/types.proto
  proto/tendermint/services/block_results/v1/block_results.pb.go
  proto/tendermint/services/block_results/v1/block_results.proto
  proto/tendermint/services/block_results/v1/block_results_service.pb.go
  proto/tendermint/services/block_results/v1/block_results_service.proto
  proto/tendermint/types/validator.proto
  rpc/grpc/client/block_results_service.go
  rpc/grpc/client/client.go
  rpc/grpc/client/version_service.go
  rpc/grpc/server/server.go
  rpc/grpc/server/services/blockresultservice/service.go
  test/e2e/tests/grpc_test.go
Labels: grpc

#1150 ADR 101: Implement pruning mechanism
  .changelog/unreleased/breaking-changes/1096-state-store-adr101-methods.md
  .changelog/unreleased/enhancements/1096-config-pruner.md
  .changelog/unreleased/enhancements/1096-node-pruner.md
  .changelog/unreleased/enhancements/1096-state-abcires-pruning.md
  .changelog/unreleased/enhancements/1096-state-background-pruning.md
  config/config.go
  config/toml.go
  consensus/replay_test.go
  docs/core/configuration.md
  node/node.go
  node/node_test.go
  rpc/test/helpers.go
  state/errors.go
  state/execution.go
  state/export_test.go
  state/mocks/store.go
  state/pruner.go
  state/pruner_observer.go
  state/store.go
  state/store_test.go
  store/store.go
  store/store_test.go
  test/e2e/tests/block_test.go
Labels: P:storage-optimization

#1208 Add check for non-`nil` in `enterCommit`
  consensus/state.go
  consensus/state_test.go
Labels: consensus

#1079 Log proposer's address when correctly accepting a proposal
  consensus/state.go
  state/execution.go
Labels: backport-to-v0.34.x, backport-to-v0.37.x, logs, backport-to-v0.38.x

#1210 Close evidence.db OnStop
  .changelog/unreleased/improvements/1210-close-evidence-db.md
  node/node.go
Labels: bug, backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x

#1167 Remove WebSocket endpoint altogether (feature branch)
  .changelog/unreleased/breaking-changes/1167-rm-websocket.md
  UPGRADING.md
  cmd/cometbft/commands/debug/dump.go
  cmd/cometbft/commands/debug/kill.go
  cmd/cometbft/commands/light.go
  config/config.go
  config/config_test.go
  config/toml.go
  consensus/state.go
  docs/app-dev/indexing-transactions.md
  docs/core/README.md
  docs/core/configuration.md
  docs/core/running-in-production.md
  docs/core/subscription.md
  go.mod
  go.sum
  inspect/inspect_test.go
  inspect/rpc/rpc.go
  light/provider/http/http.go
  light/provider/http/http_test.go
  light/proxy/proxy.go
  light/proxy/routes.go
  light/rpc/client.go
  node/node.go
  rpc/client/event_test.go
  rpc/client/evidence_test.go
  rpc/client/examples_test.go
  rpc/client/helpers.go
  rpc/client/http/http.go
  rpc/client/interface.go
  rpc/client/mock/client.go
  rpc/client/mocks/client.go
  rpc/client/rpc_test.go
  rpc/core/events.go
  rpc/core/mempool.go
  rpc/core/routes.go
  rpc/core/tx.go
  rpc/jsonrpc/client/http_json_client.go
  rpc/jsonrpc/client/integration_test.go
  rpc/jsonrpc/client/ws_client.go
  rpc/jsonrpc/client/ws_client_test.go
  rpc/jsonrpc/doc.go
  rpc/jsonrpc/jsonrpc_test.go
  rpc/jsonrpc/server/http_json_handler.go
  rpc/jsonrpc/server/http_uri_handler.go
  rpc/jsonrpc/server/rpc_func.go
  rpc/jsonrpc/server/ws_handler.go
  rpc/jsonrpc/server/ws_handler_test.go
  rpc/jsonrpc/types/types.go
  rpc/openapi/openapi.yaml
  spec/rpc/README.md
  statesync/stateprovider.go
  test/e2e/pkg/testnet.go
Labels: rpc, breaking, wip, spike

#1191 mempool: Store peer ids as p2p.ID instead of uint16 (remove mempoolIDs)
  .changelog/unreleased/breaking-changes/1146-mempool-remove-ids.md
  mempool/ids.go
  mempool/ids_test.go
  mempool/reactor.go
  mempool/reactor_test.go
Labels: mempool

#1154 ADR-101: implement gRPC `PruningService`
  .changelog/unreleased/features/1097-pruning-service.md
  config/config.go
  config/toml.go
  node/node.go
  proto/tendermint/services/pruning/v1/pruning.pb.go
  proto/tendermint/services/pruning/v1/pruning.proto
  proto/tendermint/services/pruning/v1/service.pb.go
  proto/tendermint/services/pruning/v1/service.proto
  rpc/grpc/client/privileged/privileged.go
  rpc/grpc/client/privileged/pruning_service.go
  rpc/grpc/server/privileged/privileged.go
  rpc/grpc/server/services/pruningservice/service.go
  rpc/test/helpers.go
  test/e2e/pkg/infra/docker/docker.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
  test/e2e/tests/grpc_test.go
Labels: adr, grpc

#1231 consensus: Avoid process proposal when we know correct nodes validated it
  .changelog/unreleased/improvements/1230-consensus-process-proposal-once.md
  consensus/state.go
  spec/abci/abci++_methods.md
Labels: abci, consensus

#1234 ADR-101: Metrics to monitor the pruning
  node/node.go
  state/metrics.gen.go
  state/metrics.go
  state/mocks/store.go
  state/pruner.go
Labels: metrics

#1185 abci: export errors
  abci/client/client.go
  abci/client/errors.go
  abci/client/grpc_client_test.go
  abci/client/socket_client.go
  abci/server/errors.go
  abci/server/server.go
  abci/server/socket_server.go
Labels: abci, P:tech-debt, P:consensus-engine-devs

#1246 ADR-101: Pruning mechanism minor fixes
  config/config.go
  state/pruner.go
  state/store.go
Labels: P:storage-optimization

#1244 chore: Bump minimum Go version on `main` to v1.21
  .changelog/unreleased/minimum-go-version/1244-bump-go-version.md
  .github/workflows/build.yml
  .github/workflows/check-generated.yml
  .github/workflows/e2e-long-main.yml
  .github/workflows/e2e-manual-multiversion.yml
  .github/workflows/e2e-manual.yml
  .github/workflows/e2e-nightly-37x.yml
  .github/workflows/e2e-nightly-38x.yml
  .github/workflows/e2e-nightly-main.yml
  .github/workflows/e2e.yml
  .github/workflows/fuzz-nightly.yml
  .github/workflows/govulncheck.yml
  .github/workflows/lint.yml
  .github/workflows/pre-release.yml
  .github/workflows/release-version.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  DOCKER/Dockerfile
  README.md
  UPGRADING.md
  docs/guides/go-built-in.md
  docs/guides/go.md
  go.mod
  go.sum
  test/e2e/docker/Dockerfile
  test/e2e/docker/Dockerfile.debug
Labels: chore

#902 ADR 108: ADR for extending E2E infrastructure so that we can check CometBFT's behaviour with respect to ABCI++ grammar.
  docs/architecture/README.md
  docs/architecture/adr-108-e2e-abci++.md
  spec/abci/abci++_comet_expected_behavior.md
  spec/abci/abci++_example_scenarios.md
Labels: backport-to-v0.37.x, backport-to-v0.38.x

#1264 chore: log `app_hash` as hex
  .changelog/unreleased/improvements/1264-log-app-hash-as-hex.md
  state/execution.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x

#1263 update language
  docs/core/configuration.md
Labels: automerge, backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x

#1262 e2e: Scripts for random network topology generator
  test/e2e/scripts/README.md
  test/e2e/scripts/gen_manifest.py
  test/e2e/scripts/graph.py
  test/e2e/scripts/plot.py
  test/e2e/scripts/topology.py
Labels: e2e, P:bandwidth-optimization

#1017 Remove genesis persistence in state db
  .changelog/unreleased/bug-fixes/1017-remove-genesis-persistence-in-state-db.md
  blocksync/reactor_test.go
  consensus/byzantine_test.go
  consensus/common_test.go
  consensus/reactor_test.go
  consensus/replay_test.go
  node/node.go
  node/node_test.go
  node/setup.go
  state/mocks/store.go
  state/state_test.go
  state/store.go
  state/store_test.go
  state/tx_filter_test.go
  store/store_test.go
Labels: storage, wip, P:storage-optimization
