Repository cometbft/cometbft, pull requests merged in 2023-05, with the labels that each got.

#748 Updated changelog with API changes in #286
  .changelog/unreleased/breaking-changes/286-node.md
  .changelog/unreleased/breaking-changes/286-p2p.md
  CHANGELOG.md
Labels: documentation

#771 v0.37 pubsub: Handle big ints
  .changelog/unreleased/bug-fixes/771-kvindexer-parsing-big-ints.md
  .changelog/unreleased/bug-fixes/771-pubsub-parsing-big-ints.md
  docs/app-dev/indexing-transactions.md
  docs/core/subscription.md
  libs/pubsub/query/query.go
  libs/pubsub/query/query_test.go
  state/indexer/block/kv/kv.go
  state/indexer/block/kv/kv_test.go
  state/indexer/block/kv/util.go
  state/indexer/query_range.go
  state/txindex/kv/kv.go
  state/txindex/kv/kv_test.go
  state/txindex/kv/utils.go
Labels: backport-to-v0.34.x

#784 Struct `Client` exposes sensitive data
  rpc/jsonrpc/client/http_json_client.go
Labels: bug, backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x

#783 Unsafe int cast in `kill` command
  cmd/cometbft/commands/debug/kill.go
Labels: bug, backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x

#73 ADR-100: Data Companion Push API
  docs/architecture/README.md
  docs/architecture/adr-100-data-companion-push-api.md
Labels: automerge, adr

#772 ADR-103: Protobuf definition versioning
  docs/architecture/README.md
  docs/architecture/adr-103-proto-versioning.md
Labels: adr

#798 Backport of PR #771 to 0.34 : big int parsing
  .changelog/unreleased/bug-fixes/771-kvindexer-parsing-big-ints.md
  .changelog/unreleased/bug-fixes/771-pubsub-parsing-big-ints.md
  docs/app-dev/indexing-transactions.md
  docs/core/subscription.md
  libs/pubsub/query/query.go
  libs/pubsub/query/query_test.go
  state/indexer/block/kv/kv.go
  state/indexer/block/kv/kv_test.go
  state/indexer/block/kv/util.go
  state/indexer/query_range.go
  state/txindex/kv/kv.go
  state/txindex/kv/kv_test.go
  state/txindex/kv/utils.go
Labels: bug, indexer, rpc

#817 ADR-103: Protobuf definition versioning (#772)
  docs/architecture/README.md
  docs/architecture/adr-103-proto-versioning.md
Labels: adr

#829 rpc: Remove response data from response failure logs
  rpc/jsonrpc/server/http_json_handler.go
  rpc/jsonrpc/server/http_server.go
  rpc/jsonrpc/server/http_uri_handler.go
Labels: backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x

#797 pubsub/kvindexer:support for big numbers - v2
  docs/app-dev/indexing-transactions.md
  docs/core/subscription.md
  internal/indexer/indexer_utils.go
  libs/pubsub/query/query.go
  libs/pubsub/query/query_test.go
  libs/pubsub/query/syntax/parser.go
  node/setup.go
  state/indexer/block.go
  state/indexer/block/kv/kv.go
  state/indexer/block/kv/kv_test.go
  state/indexer/block/kv/util.go
  state/indexer/block/null/null.go
  state/indexer/mocks/block_indexer.go
  state/indexer/query_range.go
  state/indexer/sink/psql/backport.go
  state/txindex/indexer.go
  state/txindex/kv/kv.go
  state/txindex/kv/kv_test.go
  state/txindex/kv/utils.go
  state/txindex/mocks/tx_indexer.go
  state/txindex/null/null.go
Labels: bug, indexer, rpc, backport-to-v0.38.x

#796 Extend the infrastructure provider with `StartNodes` and `StopTestnet`
  test/e2e/pkg/exec/exec.go
  test/e2e/pkg/infra/digitalocean/digitalocean.go
  test/e2e/pkg/infra/docker/docker.go
  test/e2e/pkg/infra/provider.go
  test/e2e/pkg/infrastructure.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/cleanup.go
  test/e2e/runner/exec.go
  test/e2e/runner/main.go
  test/e2e/runner/perturb.go
  test/e2e/runner/setup.go
  test/e2e/runner/start.go
  test/e2e/runner/test.go
  test/e2e/tests/e2e_test.go
  test/e2e/tests/net_test.go
Labels: e2e

#846 Digital Ocean implementation of `StartNodes` and `StopTestnet`
  test/e2e/pkg/infra/digitalocean/digitalocean.go
Labels: e2e, backport-to-v0.38.x

#847 feature/adr101: Sync with `main`
  docs/app-dev/indexing-transactions.md
  docs/architecture/README.md
  docs/architecture/adr-103-proto-versioning.md
  docs/core/subscription.md
  go.mod
  go.sum
  internal/indexer/indexer_utils.go
  libs/pubsub/query/query.go
  libs/pubsub/query/query_test.go
  libs/pubsub/query/syntax/parser.go
  node/setup.go
  rpc/jsonrpc/server/http_json_handler.go
  rpc/jsonrpc/server/http_server.go
  rpc/jsonrpc/server/http_uri_handler.go
  spec/p2p/reactor/README.md
  spec/p2p/reactor/reactor.qnt
  state/indexer/block.go
  state/indexer/block/kv/kv.go
  state/indexer/block/kv/kv_test.go
  state/indexer/block/kv/util.go
  state/indexer/block/null/null.go
  state/indexer/mocks/block_indexer.go
  state/indexer/query_range.go
  state/indexer/sink/psql/backport.go
  state/txindex/indexer.go
  state/txindex/kv/kv.go
  state/txindex/kv/kv_test.go
  state/txindex/kv/utils.go
  state/txindex/mocks/tx_indexer.go
  state/txindex/null/null.go
  test/e2e/pkg/exec/exec.go
  test/e2e/pkg/infra/digitalocean/digitalocean.go
  test/e2e/pkg/infra/docker/docker.go
  test/e2e/pkg/infra/provider.go
  test/e2e/pkg/infrastructure.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/cleanup.go
  test/e2e/runner/exec.go
  test/e2e/runner/main.go
  test/e2e/runner/perturb.go
  test/e2e/runner/setup.go
  test/e2e/runner/start.go
  test/e2e/runner/test.go
  test/e2e/tests/e2e_test.go
  test/e2e/tests/net_test.go
Labels: chore

#853 Release `v0.38.0-alpha.2`
  .changelog/unreleased/breaking-changes/774-state-indexerevent-remove-function-type.md
  CHANGELOG.md
  version/version.go
Labels: release

#852 `e2e` provider is extended with `Disconnect`, `Reconnect` and `CheckUpgraded`
  test/e2e/pkg/infra/digitalocean/digitalocean.go
  test/e2e/pkg/infra/docker/docker.go
  test/e2e/pkg/infra/provider.go
  test/e2e/runner/main.go
  test/e2e/runner/perturb.go
Labels: e2e

#856 proto: Restore snake_case JSON for `ExecTxResult`
  abci/types/types.pb.go
  proto/tendermint/abci/types.proto
Labels: bug, automerge, backport-to-v0.38.x

#877 qa: 200-nodes test on v0.38
  docs/qa/CometBFT-QA-38.md
  docs/qa/README.md
  docs/qa/img38/200nodes/avg_mempool_size.png
  docs/qa/img38/200nodes/block_rate.png
  docs/qa/img38/200nodes/c1r400.png
  docs/qa/img38/200nodes/cpu.png
  docs/qa/img38/200nodes/e_de676ecf-038e-443f-a26a-27915f29e312.png
  docs/qa/img38/200nodes/memory.png
  docs/qa/img38/200nodes/mempool_size.png
  docs/qa/img38/200nodes/peers.png
  docs/qa/img38/200nodes/rounds.png
  docs/qa/img38/200nodes/total_txs_rate.png
  docs/qa/img38/200nodes/v038_report_tabbed.txt
  scripts/qa/reporting/prometheus_plotter.py
Labels: qa

#883 qa: rotating node test on `v0.38.x`
  docs/qa/CometBFT-QA-38.md
  docs/qa/img37/rotating/rotating_avg_memory.png
  docs/qa/img37/rotating/rotating_block_rate.png
  docs/qa/img37/rotating/rotating_cpu.png
  docs/qa/img37/rotating/rotating_eph_heights.png
  docs/qa/img37/rotating/rotating_peers.png
  docs/qa/img37/rotating/rotating_txs_rate.png
  docs/qa/img38/rotating/rotating_avg_memory.png
  docs/qa/img38/rotating/rotating_block_rate.png
  docs/qa/img38/rotating/rotating_cpu.png
  docs/qa/img38/rotating/rotating_eph_heights.png
  docs/qa/img38/rotating/rotating_latencies.png
  docs/qa/img38/rotating/rotating_peers.png
  docs/qa/img38/rotating/rotating_txs_rate.png
  scripts/qa/reporting/README.md
  scripts/qa/reporting/prometheus_plotter.py
Labels: qa, backport-to-v0.38.x

#878 Changes to QA related files (e.g., `method.md`)
  RELEASES.md
  docs/qa/method.md
  scripts/qa/reporting/README.md
  scripts/qa/reporting/latency_plotter.py
Labels: qa, backport-to-v0.38.x

#801 ADR-104: Out-of-band state sync support
  docs/architecture/README.md
  docs/architecture/adr-104-out-of-band-state-sync.md
Labels: wip

#894 mempool: slight refactor for improving readability
  mempool/clist_mempool.go
  mempool/mempoolTx.go
  mempool/reactor.go
Labels: mempool, backport-to-v0.37.x, backport-to-v0.38.x
