Repository cometbft/cometbft, pull requests merged in 2024-03, with the labels that each got.

#2321 feat(consensus): improve logging for timely and untimely messages
  internal/consensus/state.go
Labels: logs, pbts

#2489 feat(types): improve Proposal and SynchronyParams validation tests
  internal/consensus/msgs_test.go
  types/canonical.go
  types/params.go
  types/params_test.go
  types/proposal.go
  types/proposal_test.go
Labels: pbts, testing

#2492 test(consensus): refactor TestStateLock_POLSafety tests
  internal/consensus/state_test.go
Labels: consensus, testing

#2490 feat(types): refactor types.AdaptiveSynchronyParams method
  internal/consensus/pbts_test.go
  internal/consensus/state.go
  types/params.go
  types/params_test.go
Labels: pbts

#2496 feat(privval)!: DO NOT require extension signature
  .changelog/unreleased/improvements/2496-privval-ext-signature.md
  api/cometbft/privval/v1/types.pb.go
  internal/consensus/common_test.go
  internal/consensus/invalid_test.go
  internal/evidence/verify_test.go
  internal/state/validation_test.go
  internal/test/commit.go
  privval/file.go
  privval/file_test.go
  privval/retry_signer_client.go
  privval/signer_client.go
  privval/signer_client_test.go
  privval/signer_requestHandler.go
  proto/cometbft/privval/v1/types.proto
  types/block_test.go
  types/evidence.go
  types/priv_validator.go
  types/validation_test.go
  types/vote.go
  types/vote_set_test.go
  types/vote_test.go
Labels: backport-to-v1.x

#2519 refactor(privval): rename sign_extension to skip_sign_extension
  .changelog/unreleased/improvements/2496-privval-ext-signature.md
  api/cometbft/privval/v1/types.pb.go
  privval/signer_client.go
  privval/signer_requestHandler.go
  proto/cometbft/privval/v1/types.proto
Labels: backport-to-v1.x

#2493 fix(pbts): block Time must be Canonical
  internal/blocksync/reactor_test.go
  internal/consensus/common_test.go
  internal/consensus/wal_test.go
  internal/state/helpers_test.go
  internal/state/validation.go
  internal/state/validation_test.go
  internal/test/validator.go
Labels: pbts, testing

#2454 feat(e2e): Add manifest option `clock_skew` and corresponding backend functionality
  .changelog/unreleased/improvements/2453-e2e-add-clock-skew.md
  cmd/cometbft/commands/debug/dump.go
  common.mk
  internal/consensus/metrics.go
  internal/consensus/msgs_test.go
  internal/consensus/pbts_test.go
  internal/consensus/reactor.go
  internal/consensus/wal_test.go
  internal/state/execution.go
  internal/state/execution_test.go
  internal/state/rollback_test.go
  internal/state/validation_test.go
  internal/statesync/stateprovider.go
  internal/statesync/syncer_test.go
  libs/log/cmtfmt_logger.go
  libs/log/cmtfmt_logger_test.go
  light/example_test.go
  light/rpc/client.go
  light/store/db/db_test.go
  light/verifier_test.go
  node/node_test.go
  privval/signer_client_test.go
  rpc/jsonrpc/server/http_server.go
  test/e2e/Makefile
  test/e2e/docker/Dockerfile
  test/e2e/docker/Dockerfile.debug
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
  test/e2e/pkg/infra/digitalocean/digitalocean.go
  test/e2e/pkg/infra/docker/docker.go
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/tests/validator_test.go
  types/block_test.go
  types/event_bus_test.go
  types/evidence_test.go
  types/light_test.go
  types/time/now.go
  types/time/now_skew.go
  types/time/time.go
  types/validation_test.go
Labels: qa, e2e, pbts

#2498 fix(mempool): converting to uint64 before additions to avoid overflows
  mempool/clist_mempool.go
Labels: backport-to-v1.x

#2522 refactor!: Rename `skip_sign_extension` to `skip_extension_signing`
  .changelog/unreleased/improvements/2496-privval-ext-signature.md
  .changelog/unreleased/improvements/2522-privval-skip-extension-signing.md
  api/cometbft/privval/v1/types.pb.go
  privval/signer_client.go
  privval/signer_requestHandler.go
  proto/cometbft/privval/v1/types.proto
  proto/tendermint/privval/types.proto
Labels: protobuf, backport-to-v1.x

#2488 feat(e2e): add generator support for clock skew + env variable rename
  test/e2e/generator/generate.go
  test/e2e/pkg/infra/docker/docker.go
  types/time/now_skew.go
Labels: qa, e2e, pbts

#2550 chore: improving error handling in the PendingEvidence
  internal/evidence/pool.go
Labels: backport-to-v1.x

#2467 feat(blocksync)!: set the max number of (concurrently) downloaded blocks to {peersCount * 20}
  .changelog/unreleased/improvements/2467-decrease-n-of-requested-blocks.md
  internal/blocksync/pool.go
  internal/blocksync/pool_test.go
  internal/blocksync/reactor.go
  internal/blocksync/reactor_test.go
Labels: backport-to-v1.x

#2515 feat(blocksync): set the max number of (concurrently) downloaded blocks (backport #2467)
  .changelog/unreleased/improvements/2467-decrease-n-of-requested-blocks.md
  blocksync/pool.go
  blocksync/pool_test.go
  blocksync/reactor.go
Labels: backport-to-v0.34.x, backport-to-v0.37.x

#2475 feat(blocksync): sort peers by download rate & multiple requests for closer blocks
  .changelog/unreleased/improvements/2475-blocksync-2nd-request.md
  .changelog/unreleased/improvements/2475-blocksync-no-block-response.md
  .changelog/unreleased/improvements/2475-blocksync-sort-peers.md
  internal/blocksync/pool.go
  internal/blocksync/reactor.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#2578 feat(pbts): Adjusts PBTS metrics buckets
  internal/consensus/metrics.gen.go
  internal/consensus/metrics.go
  types/params.go
Labels: backport-to-v1.x, pbts

#2574 feat(blocksync): set the max number of (concurrently) downloaded bloc…
  .changelog/unreleased/improvements/2467-decrease-n-of-requested-blocks.md
  blocksync/pool.go
  blocksync/pool_test.go
  blocksync/reactor.go
Labels: block-sync

#2584 fix(blocksync): use timer instead of time.After
  internal/blocksync/pool.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#861 Adds the Gossip CRDT
  spec/consensus/gossip/README.md
  spec/consensus/gossip/architecture.md
  spec/consensus/gossip/crdt.md
  spec/consensus/gossip/crdt.qnt
  spec/consensus/gossip/gossip.md
  spec/consensus/gossip/option.qnt
  spec/consensus/gossip/sse.qnt
Labels: wip

#2589 fix: temporary fix for `api` dependency
  RELEASES.md
  go.mod
  go.sum
Labels: bug, backport-to-v1.x, pbts

#2590 Release v0.34.32
  .changelog/v0.34.32/bug-fixes/1749-light-client-attack-verify-all-sigs.md
  .changelog/v0.34.32/improvements/1715-validate-validator-address.md
  .changelog/v0.34.32/improvements/1730-increase-abci-socket-message-size-limit.md
  .changelog/v0.34.32/improvements/2094-e2e-load-max-txs.md
  .changelog/v0.34.32/improvements/2328-e2e-log-sent-txs.md
  .changelog/v0.34.32/summary.md
  CHANGELOG.md
  version/version.go
Labels: release

#2591 Release v0.37.5
  .changelog/v0.37.5/bug-fixes/1687-consensus-fix-block-validation.md
  .changelog/v0.37.5/bug-fixes/1749-light-client-attack-verify-all-sigs.md
  .changelog/v0.37.5/improvements/1715-validate-validator-address.md
  .changelog/v0.37.5/improvements/1730-increase-abci-socket-message-size-limit.md
  .changelog/v0.37.5/improvements/2467-decrease-n-of-requested-blocks.md
  .changelog/v0.37.5/improvements/2475-blocksync-2nd-request.md
  .changelog/v0.37.5/improvements/2475-blocksync-no-block-response.md
  .changelog/v0.37.5/improvements/2475-blocksync-sort-peers.md
  .changelog/v0.37.5/summary.md
  CHANGELOG.md
  version/version.go
Labels: release

#2592 Release v0.38.6
  .changelog/v0.38.6/bug-fixes/2047-privval-retry-accepting-conn.md
  .changelog/v0.38.6/bug-fixes/2136-fix-state-rollback.md
  .changelog/v0.38.6/features/2362-e2e-block-max-bytes.md
  .changelog/v0.38.6/improvements/2016-blocksync-avoid-double-calling-block-from-proto.md
  .changelog/v0.38.6/improvements/2094-e2e-load-max-txs.md
  .changelog/v0.38.6/improvements/2434-jsonrpc-websocket-basic-auth.md
  .changelog/v0.38.6/improvements/2467-decrease-n-of-requested-blocks.md
  .changelog/v0.38.6/improvements/2475-blocksync-2nd-request.md
  .changelog/v0.38.6/improvements/2475-blocksync-no-block-response.md
  .changelog/v0.38.6/improvements/2475-blocksync-sort-peers.md
  .changelog/v0.38.6/summary.md
  CHANGELOG.md
  version/version.go
Labels: release

#2597 fix(e2e): Add clock skew only to processes that accumulate less than 1/3 of voting power
  test/e2e/generator/generate.go
Labels: bug, e2e, backport-to-v1.x

#2536 docs: format error in ABCI++ specs under commit and listsnapshots section
  spec/abci/abci++_methods.md
Labels: documentation, backport-to-v0.38.x, backport-to-v1.x

#2600 docs: Copy description of section on compaction to docs
  docs/explanation/core/configuration.md
Labels: documentation, backport-to-v1.x

#2605 fix(e2e): Increase waiting timeout when killing, pausing, or restarting a node
  test/e2e/runner/perturb.go
Labels: e2e, backport-to-v1.x

#2606 fix(e2e): Increase timeout when waiting for new block
  test/e2e/tests/app_test.go
Labels: e2e, backport-to-v1.x

#2615 fix(monitoring): Do not convert ms to ms
  test/monitoring/config-grafana/provisioning/dashboards-data/storage.json
Labels: backport-to-v1.x

#2200 refactor(rpc): export rpc package errors
  .changelog/unreleased/improvements/2200-export-rpc-packager-errors.md
  rpc/client/errors.go
  rpc/client/helpers.go
  rpc/client/helpers_test.go
  rpc/client/local/local.go
  rpc/core/blocks.go
  rpc/core/env.go
  rpc/core/errors.go
  rpc/core/events.go
  rpc/core/evidence.go
  rpc/core/mempool.go
  rpc/core/net.go
  rpc/core/tx.go
  rpc/grpc/client/block_results_service.go
  rpc/grpc/client/block_service.go
  rpc/grpc/client/client.go
  rpc/grpc/client/errors.go
  rpc/grpc/client/privileged/privileged.go
  rpc/grpc/errors/errors.go
  rpc/grpc/server/server.go
  rpc/jsonrpc/client/errors.go
  rpc/jsonrpc/client/http_json_client.go
  rpc/jsonrpc/client/http_uri_client.go
  rpc/jsonrpc/server/errors.go
  rpc/jsonrpc/server/http_server.go
  rpc/jsonrpc/server/ws_handler.go
Labels: rpc, P:tech-debt

#2596 docs: report on storage changes and decisions.
  .changelog/unreleased/features/2596-storage-report.md
  docs/references/README.md
  docs/references/storage/README.md
  docs/references/storage/img/e2e_block_store_access_time.png
  docs/references/storage/img/e2e_commit_time.png
  docs/references/storage/img/e2e_state_store_access_time.png
  docs/references/storage/img/e2e_storage_usage.png
  docs/references/storage/img/e2e_val_missed_blocks.png
  docs/references/storage/img/impact_compaction_local.png
  docs/references/storage/img/injective_block_processing_time.png
  docs/references/storage/img/injective_commit.png
  docs/references/storage/img/injective_compaction.png
  docs/references/storage/img/injective_no_compaction.png
  docs/references/storage/img/pebble.png
Labels: documentation, P:storage-optimization, backport-to-v1.x

#2327 feat(store)!: Support for different key layout
  .changelog/unreleased/features/2327-evidence-support-for-ordercode.md
  .changelog/unreleased/features/2327-lightdb-support-for-ordercode.md
  .changelog/unreleased/features/2327-store-support-for-ordercode.md
  cmd/cometbft/commands/inspect.go
  cmd/cometbft/commands/rollback.go
  config/config.go
  config/toml.go
  docs/explanation/core/configuration.md
  internal/evidence/pool.go
  internal/evidence/pool_test.go
  internal/inspect/inspect.go
  internal/state/export_test.go
  internal/state/store.go
  internal/state/store_test.go
  internal/statesync/stateprovider.go
  internal/store/db_key_layout.go
  internal/store/store.go
  internal/store/store_test.go
  light/store/db/db.go
  light/store/db/db_key_layout.go
  light/store/db/db_test.go
  node/node.go
  node/setup.go
  test/e2e/networks/simple.toml
  test/e2e/node/config.go
  test/e2e/node/main.go
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
Labels: P:storage-optimization

#1904 feat(light): export errors
  .changelog/unreleased/improvements/1904-export-light-package-errors.md
  light/client.go
  light/client_test.go
  light/detector.go
  light/errors.go
  light/provider/errors.go
  light/provider/http/http.go
  light/proxy/errors.go
  light/proxy/proxy.go
  light/rpc/client.go
  light/rpc/errors.go
  light/store/db/db.go
  light/store/errors.go
  light/trust_options.go
  light/verifier.go
  light/verifier_test.go
Labels: light-client, P:tech-debt

#2622 docs: some fixes to `RELEASES.md`
  RELEASES.md
Labels: documentation, backport-to-v1.x

#1901 chore: export p2p package errors
  .changelog/unreleased/improvements/1901-export-p2p-package-errors.md
  p2p/conn/connection.go
  p2p/conn/errors.go
  p2p/conn/evil_secret_connection_test.go
  p2p/conn/secret_connection.go
  p2p/conn/secret_connection_test.go
  p2p/errors.go
  p2p/netaddress.go
  p2p/netaddress_test.go
  p2p/node_info.go
  p2p/peer.go
  p2p/pex/addrbook.go
  p2p/pex/errors.go
  p2p/pex/pex_reactor.go
  p2p/switch.go
Labels: p2p, P:tech-debt

#658 docs: ADR-102 - RPC Companion
  .changelog/unreleased/improvements/658-adr-102-rpc-companion.md
  docs/references/architecture/README.md
  docs/references/architecture/adr-102-rpc-companion.md
  docs/references/architecture/images/adr-102-architecture.jpeg
Labels: documentation, adr

#2678 spec: Add missing Feature Params information in ABCI spec and some other clean-up
  spec/abci/abci++_app_requirements.md
Labels: abci, spec, P:tech-debt, backport-to-v1.x

#850 docs: ADR-106: gRPC API
  docs/references/architecture/README.md
  docs/references/architecture/adr-106-grpc-api.md
Labels: wip, adr

#2686 fix: don't check Synchrony params when PBTS is not enabled
  types/params.go
  types/params_test.go
Labels: backport-to-v1.x, pbts

#2682 fix(changelog): fix entry in `v1.x` which doesn't have extension `.md`
  .changelog/unreleased/improvements/1518-reduce-default-maxbytes_increase_maxgas.md
Labels: documentation
