Repository cometbft/cometbft, pull requests merged in 2024-05, with the labels that each got.

#2948 docs: merging configuration documents
  .changelog/unreleased/improvements/2769-merge-config-docs.md
  docs/explanation/core/configuration.md
  docs/references/config/config.toml.md
Labels: documentation, config, hygiene, backport-to-v1.x

#2949 perf(p2p/channel): Speedup NewDelimitedWriter
  .changelog/unreleased/improvements/2949-reduce-protoio-writer-creation-time.md
  internal/protoio/writer.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#2950 perf(p2p): Remove unnecessary atomic read
  p2p/conn/connection.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#2952 perf(p2p/conn): Remove a minint call that was appearing in write packet delays
  .changelog/unreleased/improvements/2952-lower-next-packet-msg-time.md
  p2p/conn/connection.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#2953 refactor(p2p/connection): Slight refactor to sendManyPackets that helps highlight performance improvements
  p2p/conn/connection.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#2959 perf(internal/bits): Speedup extended commit.BitArray()
  .changelog/unreleased/improvements/2959-speedup-initialized-bitarray-construction.md
  internal/bits/bit_array.go
  internal/bits/bit_array_test.go
  types/block.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#2984 fix(metric): message type in metric `MessageReceiveBytesTotal` is wrong
  p2p/peer.go
Labels: bug, metrics, backport-to-v1.x

#2897 docs(ADR-114): Partly Undo ADR 109 (Reduce Go API Surface)
  docs/references/architecture/README.md
  docs/references/architecture/adr-114-undo-109.md
Labels: backport-to-v1.x

#2986 perf(p2p/connection): Lower wasted re-allocations in sendRoutine
  .changelog/unreleased/improvements/2986-lower-memory-allocation-in-packet-writing.md
  p2p/conn/connection.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#2964 perf(consensus/blockstore): Remove validate basic call from LoadBlockMeta
  .changelog/unreleased/improvements/2964-skip-revalidation-of-blockstore-LoadBlockFromMeta-.md
  store/store.go
  types/block_meta.go
  types/block_meta_test.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#2999 perf(p2p): lower `flush_throttle_timeout`
  .changelog/unreleased/improvements/2988-flush-throttle-timeout.md
  config/config.go
  docs/references/config/config.toml.md
  p2p/conn/connection.go
  spec/p2p/implementation/configuration.md
Labels: backport-to-v1.x

#3000 fix: remove comment about default value (#2867)
  rpc/jsonrpc/server/http_server.go
Labels: backport-to-v0.38.x, hygiene, backport-to-v1.x

#2895 feat(config)!: merge `timeout_prevote` and `timeout_precommit`
  .changelog/unreleased/breaking-changes/2895-merge-timeout-prevote-precommit.md
  config/config.go
  config/config_test.go
  config/toml.go
  docs/references/config/config.toml.md
  internal/consensus/invalid_test.go
  internal/consensus/state_test.go
Labels: backport-to-v1.x

#3015 docs: fix merge for configuration doc v1
  docs/explanation/core/configuration.md
Labels: documentation, hygiene

#2268 fix(mempool): Fix data race when rechecking with async ABCI client
  .changelog/unreleased/bug-fixes/1827-fix-recheck-async.md
  .changelog/unreleased/improvements/1827-config-mempool-recheck-timeout.md
  config/config.go
  config/toml.go
  docs/references/config/config.toml.md
  mempool/clist_mempool.go
  mempool/clist_mempool_test.go
Labels: bug, mempool, backport-to-v0.38.x, backport-to-v1.x

#3018 perf: Micro optimization to save one allocation per packet
  .changelog/unreleased/improvements/3019-reduce-allocations-in-packet-reads.md
  libs/protoio/io.go
  libs/protoio/reader.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#3017 perf: Minor speedup to consenus metrics MarkLateVote
  .changelog/unreleased/improvements/3017-speedup-consensus-metrics.md
  internal/consensus/metrics.go
  types/signed_msg_type.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#3033 docs: add missing param for NewNode
  docs/tutorials/go-built-in.md
Labels: backport-to-v1.x

#3034 docs: disambiguate protocol version
  spec/abci/abci++_methods.md
  spec/core/data_structures.md
Labels: backport-to-v1.x

#3051 chore: remove repetitive words
  internal/consensus/state.go
  internal/consensus/state_test.go
  mempool/reactor_test.go
Labels: spelling

#2960 perf(consensus): align calls to `ValidateBlock`, `ProcessProposal` and `isTimely`
  internal/consensus/state.go
Labels: consensus

#3057 feat(config): use embed pkg for the default template
  .changelog/unreleased/improvements/3057-use-embed-pkg-for-template-string.md
  config/config.toml.tpl
  config/toml.go
Labels: backport-to-v1.x

#3074 chore(deps): remove `minio/sha256-simd`
  crypto/bls12381/key_bls12381.go
  go.mod
  go.sum
Labels: backport-to-v1.x

#3052 refactor: improve debug information in HTTP handler logging
  rpc/jsonrpc/server/http_uri_handler.go
Labels: rpc, logs

#3078 chore: fix function names in comment
  config/config.go
  internal/consensus/pbts_test.go
Labels: spelling

#3003 perf(blockstore): Add LRU caches to blockstore operations used in consensus
  .changelog/unreleased/improvements/3003-use-lru-caches-in-blockstore.md
  .golangci.yml
  go.mod
  go.sum
  store/bench_test.go
  store/store.go
  store/store_test.go
  types/block.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#3077 fix(proto): deprecate `pub_key` in `Validator` instead of removing it
  .changelog/unreleased/breaking-changes/2878-proto-types-validator-public-key.md
  api/cometbft/types/v1/validator.pb.go
  proto/cometbft/types/v1/validator.proto
  types/validator.go
Labels: backport-to-v1.x

#3092 fix: TimeoutTicker returns wrong value/timeout pair when timeouts are scheduled at ~approximately the same time
  .changelog/unreleased/bug-fixes/3092-consensus-timeout-ticker-data-race.md
  internal/consensus/ticker.go
  internal/consensus/ticker_test.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#3072 docs: adding ABCI error information
  abci/example/kvstore/kvstore.go
  docs/tutorials/go-built-in.md
  docs/tutorials/go.md
  spec/abci/abci++_basic_concepts.md
Labels: documentation, abci

#3103 refactor: Minor code de-duplication in timeout calculation
  config/config.go
Labels: hygiene, backport-to-v1.x

#3086 feat(types): test consensus breakage
  types/consensus_breakage_test.go
Labels: backport-to-v1.x

#3104 refactor: unlock logic
  privval/signer_server.go
Labels: hygiene, backport-to-v1.x

#3016 perf: Speedup flowrate by removing time.Now() from every update call
  .changelog/unreleased/improvements/3016-remove-expensive-calls-from-flowrate.md
  internal/flowrate/flowrate.go
  internal/flowrate/util.go
Labels: stale

#3119 chore: remove duplicated words
  docs/references/rfc/tendermint-core/rfc-013-abci++.md
  docs/references/rfc/tendermint-core/rfc-015-abci++-tx-mutation.md
  scripts/qa/reporting/README.md
  spec/abci/abci++_methods.md
  spec/consensus/proposer-based-timestamp/v1/pbts-sysmodel_001_draft.md
Labels: spelling

#3133 spec(abci): fix TOC in abci spec
  spec/abci/abci++_app_requirements.md
Labels: spec

#3116 docs(mempool): added network consistency properties and Priority Mempool
  docs/references/architecture/adr-113-mempool-lanes.md
Labels: mempool, adr

#3139 docs(mempool): comparison with Solana's Gulf Stream
  docs/references/architecture/adr-113-mempool-lanes.md
Labels: mempool, adr

#3142 test(types): add a test for the validator `Copy()` method
  types/validator_test.go
Labels: enhancement, backport-to-v1.x, testing

#3143 chore: fix the function name in comments
  abci/client/client.go
Labels: spelling

#3109 feat: add api to allow get unconfirmed_tx by hash
  .changelog/unreleased/features/3079-unconfirmed-tx.md
  internal/consensus/replay_stubs.go
  light/proxy/routes.go
  light/rpc/client.go
  mempool/clist_mempool.go
  mempool/mempool.go
  mempool/mocks/mempool.go
  mempool/nop_mempool.go
  rpc/client/http/http.go
  rpc/client/interface.go
  rpc/client/local/local.go
  rpc/client/mocks/client.go
  rpc/client/rpc_test.go
  rpc/core/mempool.go
  rpc/core/routes.go
  rpc/core/types/responses.go
Labels: events, mempool

#3141 docs(mempool): skip's Block SDK
  docs/references/architecture/adr-113-mempool-lanes.md
Labels: mempool, adr

#3134 feat(proto): add `SyncingToHeight` to `FinalizeBlockRequest`
  .changelog/unreleased/features/1247-sync-flag.md
  api/cometbft/abci/v1/types.pb.go
  internal/blocksync/reactor.go
  internal/blocksync/reactor_test.go
  internal/consensus/replay.go
  internal/consensus/replay_test.go
  internal/consensus/state.go
  proto/cometbft/abci/v1/types.proto
  spec/abci/abci++_methods.md
  state/execution.go
  state/execution_test.go
  state/helpers_test.go
Labels: backport-to-v1.x

#3150 docs(rpc): added entry in OpenAPI doc for new endpoint `unconfirmed_tx`
  rpc/core/mempool.go
  rpc/openapi/openapi.yaml
Labels: documentation, rpc
