Repository cometbft/cometbft, pull requests merged in 2024-04, with the labels that each got.

#2694 docs: Build app guides updated for v1
  docs/tutorials/go-built-in.md
  docs/tutorials/go.md
Labels: documentation, backport-to-v1.x

#2665 feat(qa): take parameters from command arguments in python scripts
  scripts/qa/reporting/README.md
  scripts/qa/reporting/latency_plotter.py
  scripts/qa/reporting/latency_throughput.py
  scripts/qa/reporting/prometheus_plotter.py
Labels: qa

#2727 fix: typo in openapi schema
  rpc/openapi/openapi.yaml
Labels: spelling

#2677 docs: typo in loadtest docs
  test/loadtime/README.md
Labels: backport-to-v1.x

#2723 docs(config): added changelog entries for changes in config file
  .changelog/unreleased/features/2056-remove-unused-param.md
  .changelog/unreleased/features/2327-store-db-layout-config.md
  .changelog/unreleased/features/816-config-grpc-version-service.md
  .changelog/unreleased/features/816-config-grpc.md
  .changelog/unreleased/improvements/1324-config-genesis-hash.md
  config/toml.go
Labels: config, backport-to-v1.x

#2749 feat(lint): disable codespell for Quint (*.qnt) files
  .codespellrc
Labels: hygiene

#2684 spec: Makes some small fixes on the spec and documents some TODOs
  spec/consensus/gossip/README.md
  spec/consensus/gossip/crdt.md
  spec/consensus/gossip/crdt.qnt
  spec/consensus/gossip/gossip.md
  spec/consensus/gossip/sse.qnt
Labels: spec

#2676 chore: remove repetitive words
  docs/references/architecture/adr-102-rpc-companion.md
  docs/references/architecture/tendermint-core/adr-006-trust-metric.md
  docs/references/architecture/tendermint-core/adr-010-crypto-changes.md
  docs/references/architecture/tendermint-core/adr-054-crypto-encoding-2.md
  docs/references/architecture/tendermint-core/adr-069-flexible-node-initialization.md
  docs/references/architecture/tendermint-core/adr-075-rpc-subscription.md
  docs/references/rfc/tendermint-core/rfc-015-abci++-tx-mutation.md
  docs/references/rfc/tendermint-core/rfc-018-bls-agg-exploration.md
  docs/references/rfc/tendermint-core/rfc-024-block-structure-consolidation.md
  docs/tutorials/go.md
  internal/consensus/reactor_test.go
  internal/consensus/state.go
  spec/consensus/consensus-paper/IEEEtran.cls
  spec/ivy-proofs/accountable_safety_2.ivy
  spec/ivy-proofs/classic_safety.ivy
  spec/light-client/accountability/README.md
  spec/light-client/detection/LCDetector_003_draft.tla
  spec/light-client/verification/Lightclient_002_draft.tla
  spec/light-client/verification/Lightclient_003_draft.tla
  spec/light-client/verification/Lightclient_A_1.tla
  spec/p2p/reactor-api/p2p-api.md
  test/monitoring/README.md
Labels: documentation, hygiene, spelling

#2754 refactor(consensus): defaultDoPrevote validity checks
  internal/consensus/state.go
Labels: consensus, hygiene, backport-to-v1.x

#2352 docs(config): Configuration reference manual
  config/toml.go
  docs/references/README.md
  docs/references/config/README.md
  docs/references/config/config.toml.md
  docs/references/config/genesis.json.md
  docs/references/config/node_key.json.md
  docs/references/config/priv_validator_key.json.md
  docs/references/config/priv_validator_state.json.md
Labels: config

#2692 feat(privval)!: Allow Privval to sign arbitrary bytes.
  CHANGELOG.md
  api/cometbft/privval/v1/types.pb.go
  privval/file.go
  privval/file_test.go
  privval/msgs.go
  privval/retry_signer_client.go
  privval/signer_client.go
  privval/signer_client_test.go
  privval/signer_requestHandler.go
  privval/signer_server.go
  proto/cometbft/privval/v1/types.proto
  types/priv_validator.go
Labels: enhancement, privval, backport-to-v1.x

#2667 docs(qa/v1): Report on saturation point and 200-nodes test
  docs/references/qa/CometBFT-QA-v1.md
  docs/references/qa/README.md
  docs/references/qa/img38/200nodes/avg_mempool_size_ylim.png
  docs/references/qa/img38/200nodes/block_size_bytes.png
  docs/references/qa/img38/200nodes/memory_ylim.png
  docs/references/qa/img38/200nodes/mempool_size_max.png
  docs/references/qa/img38/200nodes/rounds_ylim.png
  docs/references/qa/img38/200nodes/total_txs_rate_ylim.png
  docs/references/qa/imgs/v1/200nodes/latencies/e_8e4e1e81-c171-4879-b86f-bce96ee2e861.png
  docs/references/qa/imgs/v1/200nodes/metrics/avg_cpu.png
  docs/references/qa/imgs/v1/200nodes/metrics/avg_memory.png
  docs/references/qa/imgs/v1/200nodes/metrics/avg_mempool_size.png
  docs/references/qa/imgs/v1/200nodes/metrics/block_rate.png
  docs/references/qa/imgs/v1/200nodes/metrics/block_rate_regular.png
  docs/references/qa/imgs/v1/200nodes/metrics/block_size_bytes.png
  docs/references/qa/imgs/v1/200nodes/metrics/blocks.png
  docs/references/qa/imgs/v1/200nodes/metrics/cpu.png
  docs/references/qa/imgs/v1/200nodes/metrics/memory.png
  docs/references/qa/imgs/v1/200nodes/metrics/mempool_size.png
  docs/references/qa/imgs/v1/200nodes/metrics/mempool_size_max.png
  docs/references/qa/imgs/v1/200nodes/metrics/peers.png
  docs/references/qa/imgs/v1/200nodes/metrics/rounds.png
  docs/references/qa/imgs/v1/200nodes/metrics/total_txs.png
  docs/references/qa/imgs/v1/200nodes/metrics/total_txs_rate.png
  docs/references/qa/imgs/v1/200nodes/metrics/total_txs_rate_regular.png
  docs/references/qa/imgs/v1/200nodes/v1_report_tabbed.txt
  docs/references/qa/imgs/v1/200nodes_with_latency_emulation/latencies/e_8190e83a-9135-444b-92fb-4efaeaaf2b52.png
  docs/references/qa/imgs/v1/200nodes_with_latency_emulation/metrics/avg_cpu.png
  docs/references/qa/imgs/v1/200nodes_with_latency_emulation/metrics/avg_memory.png
  docs/references/qa/imgs/v1/200nodes_with_latency_emulation/metrics/avg_mempool_size.png
  docs/references/qa/imgs/v1/200nodes_with_latency_emulation/metrics/block_rate.png
  docs/references/qa/imgs/v1/200nodes_with_latency_emulation/metrics/block_rate_regular.png
  docs/references/qa/imgs/v1/200nodes_with_latency_emulation/metrics/block_size_bytes.png
  docs/references/qa/imgs/v1/200nodes_with_latency_emulation/metrics/blocks.png
  docs/references/qa/imgs/v1/200nodes_with_latency_emulation/metrics/cpu.png
  docs/references/qa/imgs/v1/200nodes_with_latency_emulation/metrics/memory.png
  docs/references/qa/imgs/v1/200nodes_with_latency_emulation/metrics/mempool_size.png
  docs/references/qa/imgs/v1/200nodes_with_latency_emulation/metrics/mempool_size_max.png
  docs/references/qa/imgs/v1/200nodes_with_latency_emulation/metrics/peers.png
  docs/references/qa/imgs/v1/200nodes_with_latency_emulation/metrics/rounds.png
  docs/references/qa/imgs/v1/200nodes_with_latency_emulation/metrics/total_txs.png
  docs/references/qa/imgs/v1/200nodes_with_latency_emulation/metrics/total_txs_rate.png
  docs/references/qa/imgs/v1/200nodes_with_latency_emulation/metrics/total_txs_rate_regular.png
  docs/references/qa/imgs/v1/saturation/saturation-plotter-LE.py
  docs/references/qa/imgs/v1/saturation/saturation-plotter.py
  docs/references/qa/imgs/v1/saturation/saturation_v1_LE.png
  docs/references/qa/imgs/v1/saturation/saturation_v1_v038.png
  docs/references/qa/imgs/v1/saturation/throughput_vs_latencies_v1_with_LE.png
  docs/references/qa/imgs/v1/saturation/throughput_vs_latencies_v1_without_LE.png
  scripts/qa/reporting/prometheus_plotter.py
Labels: qa, backport-to-v1.x

#2761 docs: fixed typos in ABCI spec
  spec/abci/abci++_basic_concepts.md
Labels: backport-to-v1.x

#2285 chore: update Go version to `v1.22.0` (new MSRV for v1.x and main)
  .github/workflows/build.yml
  .github/workflows/check-generated.yml
  .github/workflows/e2e-long-main.yml
  .github/workflows/e2e-manual-multiversion.yml
  .github/workflows/e2e-manual.yml
  .github/workflows/e2e-nightly-1x.yml
  .github/workflows/e2e-nightly-37x.yml
  .github/workflows/e2e-nightly-38x.yml
  .github/workflows/e2e-nightly-main.yml
  .github/workflows/e2e.yml
  .github/workflows/fuzz-nightly.yml
  .github/workflows/govulncheck.yml
  .github/workflows/lint.yml
  .github/workflows/pre-release.yml
  .github/workflows/release-version.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  DOCKER/Dockerfile
  README.md
  api/go.mod
  api/go.sum
  docs/tutorials/go-built-in.md
  docs/tutorials/go.md
  go.mod
  go.sum
  go.work
  scripts/mockery_generate.sh
  test/docker/Dockerfile
  test/e2e/docker/Dockerfile
Labels: backport-to-v1.x

#2767 feat(config): new default value for `mempool.max_txs_bytes` parameter
  .changelog/unreleased/features/2756-mempool-max-txs-bytes.md
  config/config.go
  config/toml.go
  docs/explanation/core/configuration.md
  docs/references/config/config.toml.md
Labels: config, mempool, backport-to-v1.x

#2765 feat(crypto): add BLS12-381 curve
  .changelog/unreleased/features/2765-bls12-381-curve.md
  Makefile
  api/cometbft/crypto/v1/keys.pb.go
  common.mk
  crypto/bls12381/doc.go
  crypto/bls12381/key.go
  crypto/bls12381/key_bls12381.go
  crypto/bls12381/key_test.go
  crypto/encoding/codec.go
  go.mod
  go.sum
  internal/state/tx_filter_test.go
  proto/cometbft/crypto/v1/keys.proto
  test/e2e/Makefile
  test/e2e/docker/Dockerfile
  test/e2e/docker/Dockerfile.debug
  tests.mk
  types/block.go
  types/block_test.go
  types/params.go
  types/signable.go
Labels: backport-to-v1.x

#2774 fix(bits): prevent BitArray.UnmarshalJSON from crashing on 0 bits in the JSON
  .changelog/unreleased/bug-fixes/2774-bitarray-unmarshal-json.md
  internal/bits/bit_array.go
  internal/bits/bit_array_test.go
Labels: backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#2775 build(deps): Bump github.com/cometbft/cometbft-db from 0.11.0 to 0.12.0
  .changelog/unreleased/breaking-changes/2775-deprecate-boltdb-cleveldb.md
  config/config.go
  config/toml.go
  docs/references/config/config.toml.md
  go.mod
  go.sum
  node/node.go
Labels: backport-to-v1.x

#2788 fix(rpc): Make websocket's log on success be in Debug, not info
  .changelog/unreleased/improvements/2788-move-ws-info-log-to-debug
  rpc/jsonrpc/server/ws_handler.go
Labels: rpc, P:operator-experience

#2792 refactor(rpc): miss stop PingPongLatencyTimer
  rpc/jsonrpc/client/ws_client.go
Labels: backport-to-v0.38.x, backport-to-v1.x

#2791 fix: BootstrapState use custom genesis doc provider
  node/node.go
Labels: backport-to-v1.x

#2708 docs(qa): changes to `method.md` after running rotating node for `v1.x`
  docs/references/qa/method.md
Labels: qa

#2405 docs(qa): Update instructions on the QA methodology
  docs/references/qa/method.md
Labels: qa, backport-to-v1.x

#2714 docs(qa/v1): added section 'Rotating Node Test' to the `v1.0.0` QA report
  docs/references/qa/CometBFT-QA-38.md
  docs/references/qa/CometBFT-QA-v1.md
  docs/references/qa/imgs/v1/rotating/latencies.png
  docs/references/qa/imgs/v1/rotating/metrics/rotating_avg_memory.png
  docs/references/qa/imgs/v1/rotating/metrics/rotating_block_rate.png
  docs/references/qa/imgs/v1/rotating/metrics/rotating_cpu.png
  docs/references/qa/imgs/v1/rotating/metrics/rotating_eph_heights.png
  docs/references/qa/imgs/v1/rotating/metrics/rotating_peers.png
  docs/references/qa/imgs/v1/rotating/metrics/rotating_txs_rate.png
  scripts/qa/reporting/latency_plotter.py
  scripts/qa/reporting/prometheus_plotter.py
  scripts/qa/reporting/requirements.txt
Labels: qa, backport-to-v1.x

#2786 feat!: remove cleveldb and boltdb
  .changelog/unreleased/breaking-changes/2775-deprecate-boltdb-cleveldb.md
  .changelog/unreleased/breaking-changes/2786-remove-cleveldb-boltdb.md
  cmd/cometbft/commands/inspect.go
  cmd/cometbft/commands/run_node.go
  common.mk
  config/config.go
  config/toml.go
  docs/explanation/core/configuration.md
  docs/explanation/core/running-in-production.md
  docs/references/config/config.toml.md
  docs/tutorials/install.md
  node/node.go
  test/e2e/Makefile
  test/e2e/docker/Dockerfile
  test/e2e/docker/Dockerfile.debug
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
  test/e2e/networks/long.toml
  test/e2e/networks/varyVESize.toml
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
Labels: storage, P:tech-debt

#2804 refactor(rpc): allocate PingPongLatencyTimer on start
  rpc/jsonrpc/client/ws_client.go
Labels: backport-to-v0.38.x, backport-to-v1.x

#2814 docs: remove "Compile with RocksDB support"
  docs/explanation/core/running-in-production.md
  docs/tutorials/install.md
Labels: documentation

#2789 spec: fix the references for misbehavior
  spec/abci/abci++_basic_concepts.md
  spec/consensus/creating-proposal.md
  spec/consensus/evidence.md
  spec/core/data_structures.md
  types/block.go
  types/evidence.go
Labels: abci, spec, P:tech-debt, backport-to-v1.x

#2822 chore: mark state and store packages as deprecated
  state/doc.go
  store/doc.go
Labels: documentation, backport-to-v1.x

#2826 spec: remove old abci servers and fix links
  spec/abci/abci++_client_server.md
Labels: spec, P:tech-debt, hygiene, backport-to-v1.x

#2663 refactor(consensus): separate sending block parts from "pick part" logic
  internal/consensus/reactor.go
Labels: consensus, wip

#2827 chore: fix filenames and format in changelog unclog files
  .changelog/unreleased/improvements/2328-e2e-log-sent-txs.md
  .changelog/unreleased/improvements/2788-move-ws-info-log-to-debug
  .changelog/unreleased/improvements/2788-move-ws-info-log-to-debug.md
  .changelog/v0.37.0/breaking-changes/409-deprecate-blocksyncmode.md
Labels: documentation, backport-to-v0.37.x, chore, backport-to-v0.38.x, backport-to-v1.x

#2832 refactor(crypto): handle errors and more in `bls12381`
  .changelog/unreleased/features/2765-bls12-381-curve.md
  crypto/bls12381/const.go
  crypto/bls12381/key.go
  crypto/bls12381/key_bls12381.go
  crypto/bls12381/key_test.go
  test/e2e/docker/Dockerfile
  test/e2e/docker/Dockerfile.debug
Labels: backport-to-v1.x

#2845 docs(api): Added basic readme for /api directory
  api/README.md
  api/go.sum
Labels: documentation, backport-to-v1.x

#2846 perf(libs/json): Lower heap overhead of JSON encoding
  .changelog/unreleased/improvements/2846-speedup-json-encoding.md
  libs/json/encoder.go
  libs/json/encoder_test.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#2851 feat(p2p): pre-allocate static labels used to produce metrics
  p2p/metrics.go
  p2p/peer.go
  p2p/switch.go
Labels: backport-to-v1.x

#2843 feat(proto)!: replace `PubKey` in `abci.ValidatorUpdate` with `PubKeyType` and `PubKeyBytes`
  .changelog/unreleased/breaking-changes/2843-abci-types-go-api.md
  .changelog/unreleased/breaking-changes/2843-abci-types-validator-update-pubkey.md
  .changelog/unreleased/breaking-changes/2843-proto-abci-v1-validator-update.md
  abci/example/kvstore/helpers.go
  abci/example/kvstore/kvstore.go
  abci/example/kvstore/kvstore_test.go
  abci/tests/server/client.go
  abci/types/pubkey.go
  abci/types/util.go
  api/cometbft/abci/v1/types.pb.go
  crypto/encoding/codec.go
  crypto/encoding/codec_test.go
  internal/consensus/common_test.go
  internal/consensus/reactor_test.go
  internal/consensus/replay.go
  internal/consensus/replay_test.go
  proto/cometbft/abci/v1/types.proto
  proto/cometbft/types/v1/params.proto
  rpc/client/evidence_test.go
  spec/abci/abci++_methods.md
  spec/core/state.md
  state/execution.go
  state/execution_test.go
  state/helpers_test.go
  state/state_test.go
  test/e2e/app/app.go
  types/params_test.go
  types/protobuf.go
  types/protobuf_test.go
Labels: backport-to-v1.x

#2881 chore: fix function name in comment
  abci/client/socket_client_test.go
  abci/server/socket_server.go
  cmd/cometbft/commands/debug/io.go
Labels: documentation

#2820 refactor(blocksync): break up `poolRoutine`
  internal/blocksync/reactor.go
Labels: hygiene

#2839 perf(txindex): Lower allocation overhead of txIndex matchRange
  .changelog/unreleased/improvements/2839-tx_index-lower-heap-allocation.md
  state/txindex/kv/kv.go
Labels: storage, backport-to-v0.37.x, backport-to-v0.38.x, P:storage-optimization, backport-to-v1.x

#2841 perf(internal/bits): Significantly speedup bitArray.PickRandom
  .changelog/unreleased/improvements/2841-speedup-bits-pick-random.md
  internal/bits/bit_array.go
  internal/bits/bit_array_test.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#2868 docs(mempool): skeleton of QoS ADR
  docs/references/architecture/README.md
  docs/references/architecture/adr-113-mempool-lanes.md
Labels: mempool, adr

#2899 fix(bits): handle last element in PickRandom
  internal/bits/bit_array.go
  internal/bits/bit_array_test.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#2894 fix(mempool): panic when the app returns error on CheckTx request
  .changelog/unreleased/bug-fixes/2225-fix-checktx-request-returns-error.md
  mempool/clist_mempool.go
  mempool/clist_mempool_test.go
  mempool/errors.go
Labels: bug, mempool, backport-to-v0.38.x, backport-to-v1.x

#2855 perf: TxSearch pagination
  .changelog/unreleased/improvements/2855-fix-txsearch-performance.md
  internal/inspect/inspect_test.go
  rpc/core/blocks.go
  rpc/core/tx.go
  state/indexer/sink/psql/backport.go
  state/pruner_test.go
  state/txindex/indexer.go
  state/txindex/kv/kv.go
  state/txindex/kv/kv_bench_test.go
  state/txindex/kv/kv_test.go
  state/txindex/mocks/tx_indexer.go
  state/txindex/null/null.go
Labels: backport-to-v1.x

#2890 feat(proto)!: replace `pub_key` with `pub_key_type`
  .changelog/unreleased/breaking-changes/2878-proto-privval-get-pubkey-response-public-key.md
  .changelog/unreleased/breaking-changes/2878-proto-types-validator-public-key.md
  api/cometbft/privval/v1/types.pb.go
  api/cometbft/types/v1/validator.pb.go
  privval/msgs_test.go
  privval/signer_client.go
  privval/signer_client_test.go
  privval/signer_requestHandler.go
  proto/cometbft/privval/v1/types.proto
  proto/cometbft/types/v1/validator.proto
  types/validator.go
Labels: protobuf, backport-to-v1.x

#2892 feat(config)!: remove `skip_timeout_commit`
  .changelog/unreleased/breaking-changes/2892-remove-skip-timeout-commit.md
  UPGRADING.md
  config/config.go
  config/toml.go
  docs/explanation/core/configuration.md
  docs/explanation/core/running-in-production.md
  docs/references/config/config.toml.md
  internal/consensus/reactor_test.go
  internal/consensus/state.go
  internal/consensus/state_test.go
Labels: backport-to-v1.x

#2924 perf(state): Cache the block hash
  .changelog/unreleased/improvements/2924-consensus-cache-block-hash.md
  types/block.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#2933 chore: fix function names
  crypto/merkle/tree.go
  internal/events/events_test.go
  libs/math/fraction.go
Labels: documentation, spelling

#2911 perf(event bus): Remove expensive Logger debug call in PublishEventTx
  .changelog/unreleased/improvements/2911-remove-event-bus-debug-logs.md
  types/event_bus.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x

#2929 spec(abci): slight improvements to ABCI spec (@angrav's feedback from Anoma)
  spec/abci/abci++_basic_concepts.md
  spec/abci/abci++_comet_expected_behavior.md
  spec/abci/abci++_methods.md
Labels: abci, spec, backport-to-v0.38.x, backport-to-v1.x

#2928 perf(consensus/state): Change finalizeCommit to use applyVerifiedBlock
  .changelog/unreleased/improvements/2928-remove-redundant-verifyblock-call-in-finalize-commit.md
  internal/consensus/state.go
Labels: backport-to-v0.37.x, backport-to-v0.38.x, backport-to-v1.x
