Repository cometbft/cometbft, pull requests merged in 2024-01, with the labels that each got.

#1876 Extend kvstore example add with with key types
  abci/example/kvstore/README.md
  abci/example/kvstore/helpers.go
  abci/example/kvstore/kvstore.go
Labels: enhancement, wip, backport-to-v0.38.x, backport-to-v1.x

#1877 Extra check in `VerifyExtension`
  types/vote.go
Labels: wip, backport-to-v1.x

#1921 perf(crypto/merkle, crypto/tmhash): simplify+optimize SHA256 hashing of multiple byteslices
  .changelog/unreleased/improvements/1921-crypto-merkle-innerHash.md
  crypto/merkle/bench_test.go
  crypto/merkle/hash.go
  crypto/tmhash/bench_test.go
  crypto/tmhash/hash.go
Labels: backport-to-v0.38.x, backport-to-v1.x

#1975 Update localnet-start Makefile
  networks/local/Makefile
Labels: backport-to-v0.38.x, backport-to-v1.x

#1879 blocksync: wait for poolRoutine to stop in (*Reactor).OnStop
  .changelog/unreleased/bug-fixes/1879-blocksync-wait-for-pool-routine.md
  internal/blocksync/reactor.go
Labels: backport-to-v0.38.x, backport-to-v1.x

#1947 fix TestListenerTimeoutReadWrite
  privval/socket_listeners_test.go
Labels: backport-to-v0.38.x, backport-to-v1.x

#1988 docs: fix typos
  docs/architecture/tendermint-core/adr-042-state-sync.md
  docs/architecture/tendermint-core/adr-045-abci-evidence.md
  docs/architecture/tendermint-core/adr-056-light-client-amnesia-attacks.md
Labels: spelling

#1900 feat: DefaultHttpClient support setting proxy from env
  .changelog/unreleased/improvements/1900-httpproxy-from-env.md
  rpc/jsonrpc/client/http_json_client.go
Labels: backport-to-v0.38.x, backport-to-v1.x

#1991 chore: fix typos
  docs/architecture/tendermint-core/adr-043-blockchain-riri-org.md
  docs/architecture/tendermint-core/adr-075-rpc-subscription.md
  docs/rfc/tendermint-core/rfc-018-bls-agg-exploration.md
Labels: spelling

#1996 doc:fix broken link in DOCKER/README.md
  DOCKER/README.md
Labels: documentation

#1973 PBTS: migrating to `main` the new version of the specification
  spec/consensus/proposer-based-timestamp/README.md
  spec/consensus/proposer-based-timestamp/pbts-algorithm_002_draft.md
  spec/consensus/proposer-based-timestamp/pbts-sysmodel_002_draft.md
  spec/consensus/proposer-based-timestamp/tla/Apalache.tla
  spec/consensus/proposer-based-timestamp/tla/MC_PBT.tla
  spec/consensus/proposer-based-timestamp/tla/TendermintPBT_002_draft.tla
  spec/consensus/proposer-based-timestamp/tla/typedefs.tla
  spec/consensus/proposer-based-timestamp/v1/pbts-algorithm_001_draft.md
  spec/consensus/proposer-based-timestamp/v1/pbts-sysmodel_001_draft.md
  spec/consensus/proposer-based-timestamp/v1/pbts_001_draft.md
Labels: consensus, spec

#1998 Fix paths to scripts/metricsgen in go:generate commands
  internal/blocksync/metrics.go
  internal/consensus/metrics.go
  internal/state/metrics.go
  internal/statesync/metrics.go
Labels: bug, metrics, backport-to-v1.x

#2002 chore: fix some typos
  docs/core/configuration.md
Labels: backport-to-v1.x, spelling

#2007 docs(light): fix broken link to spec
  light/doc.go
Labels: documentation, backport-to-v1.x

#2009 chore(test/loadtime): replace tm-load-test w/ cometbft-load-test
  .golangci.yml
  docs/tools/README.md
  go.mod
  go.sum
  test/loadtime/README.md
  test/loadtime/cmd/load/main.go
Labels: backport-to-v1.x

#2022 ci: Remove unused `tests` target when compiling e2e
  .github/workflows/e2e.yml
Labels: ci, hygiene

#2024 spec: fix typo in `encoding.md`
  spec/core/encoding.md
Labels: spelling

#2021 mempool: Fix data races in CListMempool's height and notifiedTxsAvailable
  .changelog/unreleased/bug-fixes/642-clist-mempool-data-races.md
  mempool/clist_mempool.go
  mempool/clist_mempool_test.go
Labels: bug, mempool, backport-to-v0.38.x, backport-to-v1.x

#2025 chore(test/loadtime): cleanup go.sum and golangci.yml
  .golangci.yml
  go.mod
  go.sum
Labels: backport-to-v1.x

#2044 misc(go.mod): remove unused peg dependency
  codecov.yml
  go.mod
  go.sum
  tools/tools.go
Labels: backport-to-v0.38.x, backport-to-v1.x

#2050 config: Remove unused `max_batch_bytes`
  config/config.go
  config/toml.go
  docs/core/configuration.md
Labels: config, hygiene, backport-to-v1.x

#2060 Backport ASA-2024-001
  .changelog/unreleased/bug-fixes/0000-asa-2024-001-fix-validate.md
  types/params.go
  types/params_test.go
Labels: bug

#2046 misc(tools)!: remove `tools` package
  go.mod
  go.sum
  scripts/mockery_generate.sh
  tools/README.md
  tools/proto/Dockerfile
  tools/tools.go
  types/params.go
Labels: backport-to-v0.38.x, backport-to-v1.x

#2070 docs(guides): add missing import
  docs/guides/go-built-in.md
  docs/guides/go.md
Labels: backport-to-v0.38.x, backport-to-v1.x

#2077 deps(localnode): bump alpine version
  networks/local/localnode/Dockerfile
Labels: backport-to-v0.38.x, backport-to-v1.x

#2074 misc(Makefile): add `help` target to display the help msg
  Makefile
Labels: backport-to-v0.38.x, backport-to-v1.x

#2066 `e2e`: test vote extension activation via `InitChain` and `FinalizeBlock`
  .changelog/unreleased/improvements/1730-increase-abci-socket-message-size-limit.md
  .changelog/unreleased/improvements/1958-disable-linting.md
  .changelog/unreleased/improvements/2065-e2e-vote-ext-activation.md
  test/e2e/app/app.go
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
  test/e2e/node/config.go
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
  types/params.go
Labels: backport-to-v1.x

#2088 Release `v0.38.4`
  .changelog/v0.38.4/improvements/2065-e2e-vote-ext-activation.md
  .changelog/v0.38.4/summary.md
  CHANGELOG.md
  store/store.go
  version/version.go
Labels: release

#2090 scripts: metricsgen parses '// metrics:' pattern
  internal/consensus/metrics.go
  scripts/metricsgen/metricsgen.go
  scripts/metricsgen/metricsgen_test.go
Labels: metrics, hygiene

#2094 e2e: Add `load_max_txs` option to manifest
  .changelog/unreleased/improvements/2094-e2e-load-max-txs.md
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/load.go
Labels: e2e

#2093 consensus: Add `chain_size_bytes` metric
  .changelog/unreleased/improvements/2093-metric-chain-size-bytes.md
  internal/consensus/metrics.gen.go
  internal/consensus/metrics.go
  internal/consensus/state.go
Labels: metrics, backport-to-v0.38.x, backport-to-v1.x

#1995 feat: conventional commits
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/conventional-pr-title.yml
  CONTRIBUTING.md
Labels: backport-to-v1.x

#2018 Forward port of tendermint/tendermint#7605, tendermint/spec#393, and tendermint/tendermint#8142
  .changelog/unreleased/features/7354-synchrony-field.md
  .changelog/unreleased/features/7376-wait-for-previous-block-time.md
  .changelog/unreleased/features/7382-new-ts-validation.md
  .changelog/unreleased/features/7391-use-pbts-for-proposal-ts.md
  .changelog/unreleased/features/7415-prevote-nil-non-timely.md
  api/cometbft/types/v1/params.pb.go
  docs/architecture/tendermint-core/adr-071-proposer-based-timestamps.md
  internal/consensus/byzantine_test.go
  internal/consensus/common_test.go
  internal/consensus/invalid_test.go
  internal/consensus/mempool_test.go
  internal/consensus/pbts_test.go
  internal/consensus/reactor.go
  internal/consensus/reactor_test.go
  internal/consensus/replay.go
  internal/consensus/replay_test.go
  internal/consensus/state.go
  internal/consensus/state_test.go
  internal/consensus/types/round_state.go
  internal/state/state.go
  internal/state/validation.go
  internal/store/store_test.go
  internal/test/config.go
  libs/time/mocks/source.go
  proto/cometbft/types/v1/params.proto
  spec/abci/abci++_methods.md
  spec/core/data_structures.md
  types/genesis_test.go
  types/params.go
  types/params_test.go
  types/proposal.go
  types/proposal_test.go
  types/time/mocks/source.go
  types/time/time.go
Labels: pbts

#2099 ci: fix permissions for "Conventional PR Title"
  .github/workflows/conventional-pr-title.yml
Labels: backport-to-v1.x

#2013 PBTS: additions and fixes on migrated spec
  docs/core/configuration.md
  light/doc.go
  spec/consensus/proposer-based-timestamp/README.md
  spec/consensus/proposer-based-timestamp/diagram.png
  spec/consensus/proposer-based-timestamp/pbts-algorithm.md
  spec/consensus/proposer-based-timestamp/pbts-algorithm_002_draft.md
  spec/consensus/proposer-based-timestamp/pbts-sysmodel.md
  spec/consensus/proposer-based-timestamp/tla/.gitignore
  spec/consensus/proposer-based-timestamp/tla/MC_PBT_2C_2F.tla
  spec/consensus/proposer-based-timestamp/tla/MC_PBT_3C_1F.tla
  spec/consensus/proposer-based-timestamp/tla/README.md
  spec/consensus/proposer-based-timestamp/tla/TendermintPBT.tla
  spec/consensus/proposer-based-timestamp/tla/experiment_data/May2022/MC_PBT_2C_2F.tla/MC.out
  spec/consensus/proposer-based-timestamp/tla/experiment_data/May2022/MC_PBT_2C_2F.tla/counterexample.itf.json
  spec/consensus/proposer-based-timestamp/tla/experiment_data/May2022/MC_PBT_2C_2F.tla/counterexample.json
  spec/consensus/proposer-based-timestamp/tla/experiment_data/May2022/MC_PBT_2C_2F.tla/counterexample.tla
  spec/consensus/proposer-based-timestamp/tla/experiment_data/May2022/MC_PBT_2C_2F.tla/log0.smt
  spec/consensus/proposer-based-timestamp/tla/experiment_data/May2022/MC_PBT_2C_2F.tla/run.txt
  spec/consensus/proposer-based-timestamp/tla/experiment_data/May2022/MC_PBT_3C_1F.tla/log0.smt
  spec/consensus/proposer-based-timestamp/tla/experiment_data/May2022/MC_PBT_3C_1F.tla/run.txt
  spec/consensus/proposer-based-timestamp/tla/experiment_data/May2022/machine.txt
  spec/consensus/proposer-based-timestamp/tla/experiment_log.md
  spec/consensus/proposer-based-timestamp/tla/runApalache.sh
  spec/consensus/proposer-based-timestamp/v1/pbts-algorithm_001_draft.md
  spec/consensus/proposer-based-timestamp/v1/pbts-sysmodel_001_draft.md
Labels: consensus, spec, pbts

#2089 PBTS: forward port of tendermint/tendermint#7709
  internal/consensus/metrics.gen.go
  internal/consensus/metrics.go
  internal/consensus/state.go
Labels: metrics, pbts

#1924 feat: use go workspace
  .gitignore
  api/go.mod
  api/go.sum
  go.work
Labels: backport-to-v1.x

#2112 fix: `ValidateUpdate`: allow no-change updates regardless of current height
  go.mod
  spec/abci/abci++_app_requirements.md
  types/params.go
  types/params_test.go
Labels: bug, backport-to-v0.38.x, backport-to-v1.x

#2117 fix: [manual backport] `ValidateUpdate`: allow no-change updates regardless of current height
  go.mod
  go.sum
  spec/abci/abci++_app_requirements.md
  types/params.go
  types/params_test.go
Labels: bug

#2108 test(localnet): Add monitoring tools for localnet
  .changelog/unreleased/features/2107-localnet-monitoring.md
  Makefile
  docker-compose.yml
  networks/local/localnode/Dockerfile
  networks/local/localnode/config-template.toml
  test/README.md
  test/monitoring/.gitignore
  test/monitoring/README.md
  test/monitoring/compose.yml
  test/monitoring/config-grafana/provisioning/alerting/.placeholder
  test/monitoring/config-grafana/provisioning/dashboards-data/main.json
  test/monitoring/config-grafana/provisioning/dashboards-data/mempool_compact.json
  test/monitoring/config-grafana/provisioning/dashboards-data/node-exporter-full.json
  test/monitoring/config-grafana/provisioning/dashboards-data/storage.json
  test/monitoring/config-grafana/provisioning/dashboards/comet.yml
  test/monitoring/config-grafana/provisioning/datasources/prometheus.yml
  test/monitoring/config-grafana/provisioning/notifiers/.placeholder
  test/monitoring/config-grafana/provisioning/plugins/.placeholder
  test/monitoring/config-prometheus/prometheus.yml
Labels: backport-to-v1.x

#2113 feat/testing: port pruning mechanism to 0.37
  .changelog/unreleased/breaking-changes/1096-state-store-adr101-methods.md
  .changelog/unreleased/enhancements/1096-config-pruner.md
  .changelog/unreleased/enhancements/1096-node-pruner.md
  .changelog/unreleased/enhancements/1096-state-abcires-pruning.md
  .changelog/unreleased/enhancements/1096-state-background-pruning.md
  config/config.go
  config/toml.go
  consensus/replay_test.go
  consensus/state.go
  docs/core/configuration.md
  go.mod
  go.sum
  node/node.go
  node/node_test.go
  rpc/test/helpers.go
  state/errors.go
  state/execution.go
  state/export_test.go
  state/metrics.gen.go
  state/metrics.go
  state/mocks/store.go
  state/pruner.go
  state/pruner_observer.go
  state/store.go
  state/store_test.go
  store/store.go
  store/store_test.go
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
  test/e2e/tests/block_test.go
  test/e2e/tests/validator_test.go
Labels: P:storage-optimization

#2049 feat: add gofumpt
  .github/workflows/codespell.yml
  .github/workflows/lint.yml
  CONTRIBUTING.md
  Makefile
  rpc/jsonrpc/client/integration_test.go
  scripts/gofumpt.sh
  test/e2e/pkg/grammar/grammar-auto/lexer/lexer.go
  test/e2e/pkg/grammar/grammar-auto/parser/bsr/bsr.go
  test/e2e/pkg/grammar/grammar-auto/parser/slot/slot.go
  test/e2e/pkg/grammar/grammar-auto/parser/symbols/symbols.go
  test/e2e/pkg/grammar/grammar-auto/sppf/sppf.go
  test/e2e/pkg/grammar/grammar-auto/token/token.go
Labels: backport-to-v1.x

#1408 feat(consensus): additional sanity checks for the size of proposed blocks
  crypto/merkle/proof.go
  internal/consensus/errors.go
  internal/consensus/state.go
  internal/consensus/state_test.go
  internal/evidence/pool_test.go
  internal/state/execution_test.go
  internal/state/store_test.go
  internal/store/store_test.go
  types/event_bus_test.go
  types/part_set.go
  types/part_set_test.go
Labels: consensus, backport-to-v0.34.x, backport-to-v0.37.x, wip, backport-to-v0.38.x, backport-to-v1.x

#2016 perf(internal/blocksync): avoid double-calling `types.BlockFromProto`
  .changelog/unreleased/improvements/2016-blocksync-avoid-double-calling-block-from-proto.md
  internal/blocksync/msgs.go
  internal/blocksync/reactor.go
Labels: backport-to-v0.38.x, backport-to-v1.x

#2156 refactor(privval): reverse conditional + more idiomatic Go code with early returns
  privval/file.go
Labels: backport-to-v1.x

#2148 fix(e2e): path to latency script files in DO
  test/e2e/pkg/infra/digitalocean/digitalocean.go
Labels: bug, e2e, backport-to-v1.x

#2123 chore(Makefile): add `setup-pre-commit` target to init git hook
  Makefile
  scripts/gofumpt.sh
  scripts/hooks/pre-commit.sh
Labels: backport-to-v1.x

#2132 feat: add pebbledb (https://github.com/cockroachdb/pebble)
  .changelog/unreleased/features/2132-cometbft-db.md
  cmd/cometbft/commands/inspect.go
  cmd/cometbft/commands/run_node.go
  common.mk
  config/config.go
  docs/explanation/core/configuration.md
  test/e2e/Makefile
  test/e2e/docker/Dockerfile
  test/e2e/docker/Dockerfile.debug
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
  test/e2e/networks/long.toml
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
Labels: backport-to-v1.x

#2026 perf(internal/blocksync): do not `ValidateBlock` twice
  internal/blocksync/reactor.go
  internal/state/execution.go
Labels: wip, backport-to-v0.38.x, backport-to-v1.x

#2192 feat(e2e): Add new targets `fast` and `clean` to Makefile
  .changelog/unreleased/improvements/2192-e2e-make-fast.md
  test/e2e/Makefile
  test/e2e/README.md
  test/e2e/fast-prototyping/README.md
Labels: e2e

#2191 ci: add `spec` type in conventional-pr-title
  .github/workflows/conventional-pr-title.yml
Labels: backport-to-v1.x

#2047 fix(privval): retry accepting a connection on errors
  .changelog/unreleased/bug-fixes/2047-privval-retry-accepting-conn.md
  privval/signer_listener_endpoint.go
  privval/signer_listener_endpoint_test.go
Labels: backport-to-v0.38.x, backport-to-v1.x

#2198 docs: update QA method steps for qa-infra changes
  docs/references/qa/method.md
Labels: documentation

#2124 docs(pbts): forward port of PBTS documentation and fixes
  docs/core/metrics.md
  docs/core/proposer-based-timestamps.md
  docs/tools/proposer-based-timestamps-runbook.md
  spec/abci/abci++_app_requirements.md
Labels: documentation, pbts
