Repository cometbft/cometbft, pull requests merged in 2024-02, with the labels that each got.

#2215 fix: if-return and early-return
  abci/example/kvstore/kvstore.go
  internal/blocksync/pool.go
  internal/consensus/types/height_vote_set.go
  internal/flowrate/io.go
  internal/store/store.go
  light/client.go
  privval/signer_dialer_endpoint.go
  rpc/jsonrpc/client/decode.go
  rpc/jsonrpc/client/ws_client.go
  rpc/jsonrpc/server/http_uri_handler.go
  test/e2e/app/state.go
  test/e2e/pkg/infra/docker/docker.go
Labels: backport-to-v1.x

#2135 chore: remove amazon linux Dockerfile and update test/docker/Dockerfile
  DOCKER/Dockerfile.build_c-amazonlinux
  DOCKER/Makefile
  Makefile
  test/docker/Dockerfile
  tests.mk
Labels: docker, backport-to-v1.x

#2214 feat(ci): pre-commit framework
  .codespellrc
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  Makefile
  scripts/hooks/pre-commit.sh
Labels: backport-to-v1.x

#2219 ci: add `merge` type for conventional-pr-title
  .github/workflows/conventional-pr-title.yml
  .github/workflows/lint.yml
  .pre-commit-config.yaml
Labels: backport-to-v1.x

#2206 spec(consensus/pbts): update description for introduced parameters.
  spec/abci/abci++_app_requirements.md
  spec/core/data_structures.md
Labels: spec, pbts

#2142 perf: optimize psql indexer
  .changelog/unreleased/improvements/2142-psql-optimization.md
  internal/state/indexer/sink/psql/psql.go
Labels: backport-to-v1.x

#2235 fix(Makefile): gofumpt no longer needed
  Makefile
Labels: backport-to-v1.x

#2010 fix(p2p/pex): gracefully shutdown `Reactor`
  .changelog/unreleased/bug-fixes/2010-p2p-pex-shutdown.md
  p2p/pex/addrbook.go
  p2p/pex/pex_reactor.go
Labels: stale, backport-to-v1.x

#2242 test(mempool): fix TestMempoolUpdateDoesNotPanicWhenApplicationMissedTx
  mempool/clist_mempool_test.go
Labels: mempool, backport-to-v1.x

#2147 fix(flowrate): fix non-determinism in flowrate tests
  internal/flowrate/io_test.go
Labels: backport-to-v1.x

#2240 refactor!: Implement RFC 106: remove `GetLatestBlock*` methods from data companion API
  .changelog/unreleased/breaking-changes/2230-rfc-106-remove-get-latest-block.md
  api/cometbft/services/block/v1/block.pb.go
  api/cometbft/services/block/v1/block_service.pb.go
  api/cometbft/services/block_results/v1/block_results.pb.go
  api/cometbft/services/block_results/v1/block_results_service.pb.go
  proto/cometbft/services/block/v1/block.proto
  proto/cometbft/services/block/v1/block_service.proto
  proto/cometbft/services/block_results/v1/block_results.proto
  proto/cometbft/services/block_results/v1/block_results_service.proto
  proto/tendermint/services/block/v1/block.proto
  proto/tendermint/services/block/v1/block_service.proto
  proto/tendermint/services/block_results/v1/block_results.proto
  proto/tendermint/services/block_results/v1/block_results_service.proto
  rpc/grpc/client/block_results_service.go
  rpc/grpc/client/block_service.go
  rpc/grpc/server/services/blockresultservice/service.go
  rpc/grpc/server/services/blockservice/service.go
  test/e2e/tests/grpc_test.go
Labels: protobuf, grpc, backport-to-v1.x

#2249 chore(config): update DB section in toml.go
  config/toml.go
Labels: backport-to-v1.x

#2221 fix(consensus): do not precommit nil if proposal block is received
  internal/consensus/state.go
  internal/consensus/state_test.go
Labels: consensus, pbts

#2263 fix(mempool/tests): Reduce tests duration
  mempool/clist_mempool.go
  mempool/clist_mempool_test.go
  mempool/reactor.go
Labels: mempool, hygiene, backport-to-v1.x

#2250 ci: run golangci-lint linters for all files (not only ones which were modified)
  .github/workflows/lint.yml
  .golangci.yml
  .pre-commit-config.yaml
  mempool/clist_mempool_test.go
Labels: backport-to-v1.x

#2272 refactor(mempool): simplify parameters of resCbFirstTime and resCbRecheck
  mempool/clist_mempool.go
  mempool/clist_mempool_test.go
Labels: mempool, backport-to-v0.38.x, hygiene, backport-to-v1.x

#2259 perf(mempool/cache): clear map in Reset
  mempool/cache.go
Labels: backport-to-v1.x

#2280 docs: symbolic references to steps in the qa-infra README
  docs/references/qa/method.md
Labels: documentation, qa, backport-to-v1.x

#2296 chore: updated doc link
  README.md
Labels: documentation, backport-to-v1.x

#2218 fix(consensus): prevote nil upon timeout when Proposal is missing
  internal/consensus/common_test.go
  internal/consensus/state.go
  internal/consensus/state_test.go
Labels: bug, consensus, backport-to-v1.x

#2223 docs: ADR-112 Proposer-Based Timestamps
  docs/references/architecture/README.md
  docs/references/architecture/adr-112-proposer-based-timestamps.md
Labels: documentation, pbts

#2294 refactor(internal/statesync): replace ticker with `time.After(X)`
  internal/statesync/syncer.go
Labels: backport-to-v1.x

#2150 fix: simultaneous rpc test failures
  rpc/jsonrpc/jsonrpc_test.go
  rpc/jsonrpc/server/http_server_test.go
Labels: backport-to-v1.x

#1892 chore(docs): alter the section about the effects of `timeout_commit`
  docs/explanation/core/configuration.md
Labels: backport-to-v0.38.x, backport-to-v1.x

#2246 refactor(p2p)!: Refactor PeerSet to eliminate data races & improve performance
  .changelog/unreleased/breaking-changes/2246-p2p-peerset.md
  .changelog/unreleased/improvements/2246-make-peerset-remove-more-efficient.md
  internal/consensus/byzantine_test.go
  internal/consensus/invalid_test.go
  internal/consensus/reactor.go
  internal/consensus/reactor_test.go
  internal/evidence/reactor_test.go
  mempool/reactor_test.go
  p2p/peer.go
  p2p/peer_set.go
  p2p/pex/pex_reactor.go
  p2p/pex/pex_reactor_test.go
  p2p/switch.go
  p2p/switch_test.go
  rpc/core/consensus.go
  rpc/core/net.go
  spec/p2p/legacy-docs/connection.md
  spec/p2p/reactor-api/p2p-api.md
Labels: backport-to-v1.x

#2231 feat(pbts): Update consensus params to include pbts enabled
  api/cometbft/types/v1/params.pb.go
  buf.gen.yaml
  internal/consensus/pbts_test.go
  internal/state/state.go
  internal/test/config.go
  proto/cometbft/types/v1/params.proto
  types/genesis_test.go
  types/params.go
  types/params_test.go
Labels: pbts

#1974 feat(storage/metrics): Metrics to measure storage
  .changelog/unreleased/features/1974-statestore-metrics.md
  .changelog/unreleased/features/1974-store-metrics.md
  internal/state/export_test.go
  internal/state/metrics.gen.go
  internal/state/metrics.go
  internal/state/store.go
  internal/store/metrics.gen.go
  internal/store/metrics.go
  internal/store/store.go
  node/node.go
  node/setup.go
  test/loadtime/basic.sh
Labels: metrics, P:storage-optimization

#2328 feat(e2e): Log number of sent txs (success and failed)
  .changelog/unreleased/improvements/2328-e2e-log-sent-txs
  test/e2e/runner/load.go
Labels: backport-to-v0.34.x, e2e, backport-to-v1.x

#2290 chore: enable gomoddirectives, unparam
  .golangci.yml
  internal/bits/bit_array.go
  light/store/db/db.go
  test/e2e/pkg/infra/digitalocean/digitalocean.go
  test/e2e/tests/e2e_test.go
Labels: backport-to-v1.x

#2331 docs: images not rendering properly in docs
  docs/imgs/light_client_bisection_alg.png
  docs/imgs/sentry_layout.png
  docs/imgs/sentry_local_config.png
Labels: documentation, backport-to-v0.34.x, backport-to-v0.37.x, backport-to-v0.38.x, hygiene, backport-to-v1.x

#2330 docs: Fix references about DeliverTx
  docs/explanation/core/running-in-production.md
  docs/explanation/core/subscription.md
  docs/explanation/introduction/README.md
Labels: documentation, backport-to-v0.38.x, hygiene, backport-to-v1.x

#2343 docs(qa): Add table of contents to existing QA reports
  docs/references/qa/CometBFT-QA-34.md
  docs/references/qa/CometBFT-QA-37.md
  docs/references/qa/CometBFT-QA-38.md
  docs/references/qa/TMCore-QA-34.md
  docs/references/qa/TMCore-QA-37.md
Labels: qa, backport-to-v1.x

#2291 chore: enable perfsprint linter
  .golangci.yml
  abci/client/errors.go
  abci/server/errors.go
  cmd/cometbft/commands/debug/dump.go
  cmd/cometbft/commands/debug/util.go
  config/config.go
  config/errors.go
  crypto/merkle/proof.go
  crypto/sr25519/privkey.go
  internal/bits/bit_array.go
  internal/consensus/common_test.go
  internal/consensus/errors.go
  internal/consensus/replay.go
  internal/consensus/state.go
  internal/os/os_test.go
  internal/state/errors.go
  internal/state/execution.go
  internal/state/indexer/block/kv/util.go
  internal/state/store_test.go
  internal/statesync/stateprovider.go
  internal/store/store.go
  libs/cli/setup_test.go
  light/provider/errors.go
  node/node.go
  node/setup.go
  p2p/peer_test.go
  p2p/switch.go
  p2p/switch_test.go
  p2p/transport_test.go
  privval/file.go
  privval/signer_listener_endpoint.go
  privval/socket_dialers_test.go
  proxy/multi_app_conn.go
  rpc/client/event_test.go
  rpc/core/blocks.go
  rpc/core/net.go
  rpc/core/tx.go
  scripts/metricsgen/metricsgen.go
  test/e2e/app/app.go
  test/e2e/pkg/grammar/checker.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/start.go
  test/loadtime/cmd/load/main.go
  types/block.go
  types/errors/sanity.go
  types/params.go
  types/validation.go
Labels: backport-to-v1.x

#2358 docs: explain how to skip pre-commit hook
  CONTRIBUTING.md
Labels: backport-to-v1.x

#2362 feat(e2e): Option to set max block size in bytes at genesis
  .changelog/unreleased/features/2362-e2e-block-max-bytes.md
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
Labels: e2e, backport-to-v0.38.x, backport-to-v1.x

#2367 fix(e2e): Reduce flakiness of TestGRPC_GetBlockResults
  test/e2e/tests/block_test.go
  test/e2e/tests/grpc_test.go
  test/e2e/tests/validator_test.go
Labels: e2e, experimental-backport, backport-to-v1.x

#2316 spec(consensus): update Block Time documentation in spec
  spec/README.md
  spec/consensus/bft-time.md
  spec/consensus/proposer-based-timestamp/README.md
  spec/consensus/readme.md
  spec/consensus/signing.md
  spec/consensus/time.md
  spec/core/data_structures.md
Labels: spec, wip, pbts

#2318 spec: adaptive MSGDELAY parameter included in PBTS spec
  spec/consensus/proposer-based-timestamp/README.md
  spec/consensus/proposer-based-timestamp/pbts-algorithm.md
  spec/consensus/proposer-based-timestamp/pbts-sysmodel.md
Labels: spec, pbts

#2383 fix(docker-compose): fix subnet
  docker-compose.yml
Labels: backport-to-v0.34.x, backport-to-v0.38.x, backport-to-v1.x

#2284 feat(pbts): enable `e2e` manifest config to set `PbtsEnableHeight`
  test/e2e/app/app.go
  test/e2e/generator/generate.go
  test/e2e/networks/ci.toml
  test/e2e/node/config.go
  test/e2e/pkg/manifest.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/setup.go
  test/e2e/tests/block_test.go
Labels: e2e, pbts

#2017 perf(internal/state): avoid double-saving FinalizeBlockResponse
  .changelog/unreleased/improvements/2017-state-avoid-double-saving-finalize-block-response.md
  internal/state/store.go
  internal/state/store_test.go
Labels: backport-to-v0.38.x, backport-to-v1.x

#2329 test(consensus): PBTS should be enabled by default in test units
  internal/consensus/byzantine_test.go
  internal/consensus/common_test.go
  internal/consensus/pbts_test.go
  internal/state/state_test.go
  internal/test/config.go
  internal/test/params.go
Labels: pbts, testing

#2404 test(consensus): test enabling PBTS at a given height
  internal/consensus/byzantine_test.go
  internal/consensus/common_test.go
  internal/consensus/pbts_test.go
  internal/consensus/replay_test.go
  internal/consensus/state.go
  internal/consensus/state_test.go
Labels: pbts, testing

#2425 refactor(protobuf): switch from gogofaster to gocosmos generator
  Makefile
  buf.gen.yaml
  scripts/proto-gen.sh
Labels: backport-to-v1.x

#2414 docs(tutorials/install): add `From Go package`
  docs/tutorials/install.md
Labels: documentation, backport-to-v0.38.x, backport-to-v1.x

#2376 docs(pbts): documentation for PBTS-related consensus parameters
  docs/explanation/core/proposer-based-timestamps.md
  docs/references/architecture/adr-112-proposer-based-timestamps.md
Labels: documentation, pbts

#2346 refactor(consensus): print err from SignAndCheckVote
  internal/consensus/state.go
  types/vote.go
  types/vote_test.go
Labels: backport-to-v0.38.x, backport-to-v1.x

#2433 feat(e2e): add parameter to set a custom output directory for testnet files
  .changelog/unreleased/features/2433-e2e-testnet-dir.md
  test/e2e/README.md
  test/e2e/generator/generate_test.go
  test/e2e/pkg/testnet.go
  test/e2e/runner/cleanup.go
  test/e2e/runner/load.go
  test/e2e/runner/main.go
  test/e2e/runner/setup.go
  test/e2e/runner/test.go
  test/e2e/tests/e2e_test.go
Labels: e2e, backport-to-v1.x

#2415 spec(consensus): update description of consensus parameters for PBTS
  api/cometbft/types/v1/params.pb.go
  proto/cometbft/types/v1/params.proto
  spec/consensus/bft-time.md
  spec/consensus/proposer-based-timestamp/README.md
  spec/consensus/proposer-based-timestamp/diagram.png
  spec/consensus/time.md
  spec/core/data_structures.md
  types/params.go
Labels: spec, pbts

#2448 fix(localnet): Grafana dashboards for storage tests - removed experimental metrics
  test/monitoring/config-grafana/provisioning/dashboards-data/storage.json
Labels: backport-to-v1.x

#2434 fix(jsonrpc): enable HTTP basic auth in WS client
  .changelog/unreleased/improvements/2434-jsonrpc-websocket-basic-auth.md
  rpc/jsonrpc/client/ws_client.go
Labels: backport-to-v0.38.x, backport-to-v1.x

#2388 feat(pbts): Adds timestamp to the `msgInfo` written into the WAL
  .changelog/unreleased/breaking/2322-removes-abci-params.md
  api/cometbft/consensus/v1/wal.pb.go
  internal/consensus/common_test.go
  internal/consensus/msgs.go
  internal/consensus/msgs_test.go
  internal/consensus/wal_test.go
  internal/state/execution_test.go
  internal/state/helpers_test.go
  internal/state/validation_test.go
  proto/cometbft/consensus/v1/wal.proto
Labels: pbts

#2447 test: untimely proposals must be decided after multiple rounds
  internal/consensus/common_test.go
  internal/consensus/pbts_test.go
Labels: consensus, pbts, testing

#2136 fix: `Rollback`: wrong modification of `state.LastHeightValidatorsChanged` while rollback at a special height
  internal/state/rollback.go
  internal/state/rollback_test.go
Labels: backport-to-v0.38.x, backport-to-v1.x

#2459 docs(changelog): add missing entry for #2136
  .changelog/unreleased/bug-fixes/2136-fix-state-rollback.md
Labels: backport-to-v0.38.x, backport-to-v1.x

#2472 feat(localnet): Grafana PNG rendering for easier graph exports
  test/monitoring/compose.yml
Labels: backport-to-v1.x

#2469 docs(README): remove Terra
  README.md
Labels: documentation, backport-to-v1.x

#2452 docs: document PBTS adaptive delays mechanism
  docs/explanation/core/proposer-based-timestamps.md
  docs/references/architecture/adr-112-proposer-based-timestamps.md
Labels: documentation, pbts

#2479 feat(metrics): more buckets for ProposalTimestampDifference
  internal/consensus/metrics.go
Labels: metrics, qa, pbts

#2481 fix(metrics): more buckets for ProposalTimestampDifference
  internal/consensus/metrics.gen.go
Labels: metrics, pbts

#2431 feat(pbts): Make synchrony params adaptive
  internal/consensus/common_test.go
  internal/consensus/pbts_test.go
  internal/consensus/state.go
  types/params.go
  types/proposal_test.go
Labels: pbts

#2483 ci: check metrics generation in CI checks
  .github/workflows/check-generated.yml
Labels: metrics, backport-to-v0.34.x, backport-to-v0.37.x, ci, backport-to-v0.38.x, backport-to-v1.x
