Repository cometbft/cometbft, pull requests merged in 2025-06, with the labels that each got.

#5136 docs(fix): Fix broken sysctls link in production guide
  docs/explanation/core/running-in-production.md
Labels: stale

#5179 refactor: cometbft image build
  .github/workflows/cometbft-docker.yml
  .github/workflows/docker-build-cometbft.yml
Labels: backport-to-v0.38.x, backport-to-v1.x

#5202 chore: update version
  version/version.go
Labels: backport-to-v2.x

#5235 fix: add libraries to e2e
  test/e2e/docker/Dockerfile
  test/e2e/docker/Dockerfile.debug
Labels: backport-to-v2.x

#5209 chore: reindex to event sink from cli
  cmd/cometbft/main.go
Labels: backport-to-v0.38.x, backport-to-v1.x, backport-to-v2.x
