Repository cometbft/cometbft, pull requests merged in 2025-01, with the labels that each got.

#4764 fix(changelog): Remove paragraph on release candidates
  CHANGELOG.md
Labels: chore, backport-to-v1.x

#4762 chore(e2e): remove `key_type` from ci manifest
  test/e2e/networks/ci.toml
Labels: automerge, e2e

#4788 fix: multiple typos of different importance
  CONTRIBUTING.md
  README.md
  STYLE_GUIDE.md
  docs/explanation/core/running-in-production.md
  docs/explanation/core/state-sync.md
Labels: spelling

#4734 chore: fix quotation marks in .md files and remove duplicate words
  CODE_OF_CONDUCT.md
  crypto/secp256k1eth/const.go
  docs/explanation/core/validators.md
  docs/references/architecture/tendermint-core/adr-001-logging.md
  docs/references/architecture/tendermint-core/adr-006-trust-metric.md
  docs/references/architecture/tendermint-core/adr-044-lite-client-with-weak-subjectivity.md
  docs/references/architecture/tendermint-core/adr-067-mempool-refactor.md
  docs/references/rfc/tendermint-core/rfc-001-storage-engine.rst
  spec/consensus/proposer-selection.md
  spec/ivy-proofs/domain_model.ivy
  spec/light-client/README.md
  test/loadtime/payload/payload.go
Labels: spelling

#4778 docs: fix typos in RELEASES.md
  RELEASES.md
Labels: spelling

#4790 docs: fix typos
  docs/guides/app-dev/indexing-transactions.md
  docs/references/config/genesis.json.md
  docs/tutorials/forum-application/3.send-message.md
Labels: spelling

#4774 docs: fix broken links
  rpc/openapi/openapi.yaml
Labels: documentation

#4771 fix: broken docs links
  docs/references/qa/method.md
  light/doc.go
Labels: documentation

#4792 docs: fix typos
  .github/linters/yaml-lint.yml
  DOCKER/README.md
  abci/cmd/abci-cli/abci-cli.go
  docs/references/architecture/tendermint-core/adr-037-deliver-block.md
  go.mod
  test/e2e/pkg/grammar/grammar-auto/lexer/lexer.go
Labels: spelling

#4793 docs: fix typos
  docs/references/architecture/tendermint-core/adr-043-blockchain-riri-org.md
  docs/references/architecture/tendermint-core/adr-056-light-client-amnesia-attacks.md
  docs/references/storage/README.md
Labels: spelling

#4675 perf(internal/bits): Additional speedup to `bitArray.PickRandom`
  .changelog/unreleased/improvements/2849-refactor-bit-array.md
  internal/bits/bit_array.go
  internal/bits/bit_array_test.go
Labels: enhancement, libs

#4847 docs: typos and update broken links
  abci/client/client.go
  docs/references/architecture/tendermint-core/adr-001-logging.md
  docs/references/architecture/tendermint-core/adr-002-event-subscription.md
  docs/references/architecture/tendermint-core/adr-007-trust-metric-usage.md
  docs/references/architecture/tendermint-core/adr-012-peer-transport.md
  docs/references/rfc/tendermint-core/rfc-024-block-structure-consolidation.md
  spec/legacy/reactors/state_sync/README.md
  spec/mempool/gossip/p2p.md
  spec/p2p/implementation/README.md
Labels: spelling

#4779 docs: fix 404 links
  docs/references/architecture/adr-107-betaize-proto-versions.md
  docs/references/rfc/rfc-102-rust-gen-builders.md
  test/e2e/pkg/grammar/grammar-auto/parser/parser.go
Labels: spelling

#4812 chore: decommission v0.34 and v0.37 release lines
  .github/mergify.yml
  .github/workflows/e2e-nightly-34x.yml
  .github/workflows/e2e-nightly-37x.yml
  CONTRIBUTING.md
  README.md
  docs/README.md
Labels: ci

#4601 build(deps): CometBFT no longer imports `cometbft-db`
  abci/example/kvstore/kvstore.go
  cmd/cometbft/commands/light.go
  cmd/cometbft/commands/reindex_event.go
  cmd/cometbft/commands/reindex_event_test.go
  cmd/cometbft/commands/rollback.go
  config/db.go
  db/db.go
  db/db_test.go
  db/pebbledb.go
  db/pebbledb_test.go
  db/prefixdb.go
  db/prefixdb_test.go
  go.mod
  go.sum
  internal/blocksync/reactor_test.go
  internal/consensus/byzantine_test.go
  internal/consensus/common_test.go
  internal/consensus/mempool_test.go
  internal/consensus/reactor_test.go
  internal/consensus/replay_test.go
  internal/consensus/wal_generator.go
  internal/consensus/wal_test.go
  internal/evidence/pool.go
  internal/evidence/pool_test.go
  internal/evidence/reactor_test.go
  internal/evidence/verify_test.go
  light/client_benchmark_test.go
  light/client_test.go
  light/detector_test.go
  light/example_test.go
  light/store/db/db.go
  light/store/db/db_test.go
  node/node_test.go
  node/setup.go
  rpc/core/blocks_test.go
  state/compatibility_test.go
  state/execution_test.go
  state/export_test.go
  state/helpers_test.go
  state/indexer/block/indexer.go
  state/indexer/block/kv/kv.go
  state/indexer/block/kv/kv_test.go
  state/pruner_test.go
  state/rollback_test.go
  state/state_test.go
  state/store.go
  state/store_test.go
  state/tx_filter_test.go
  state/txindex/indexer_service_test.go
  state/txindex/kv/kv.go
  state/txindex/kv/kv_bench_test.go
  state/txindex/kv/kv_test.go
  state/validation_test.go
  statesync/stateprovider.go
  store/store.go
  store/store_test.go
  test/loadtime/cmd/report/main.go
Labels: dependencies, storage, P:tech-debt

#4772 fix(crypto/bls12381): fix marshaling FilePVKey
  .changelog/unreleased/bug-fixes/4772-bls12381-json-marshal-privkey.md
  crypto/bls12381/key_bls12381.go
Labels: crypto, backport-to-v1.x

#4813 fix(crypto/bls12381): modify `Sign`, `Verify`
  .changelog/unreleased/bug-fixes/4783-bls12381-dstMinPk.md
  crypto/bls12381/key_bls12381.go
Labels: crypto, breaking, backport-to-v1.x

#4876 docs: fix typos and improve grammar
  CONTRIBUTING.md
  README.md
  STYLE_GUIDE.md
  docs/tutorials/go.md
  proto/README.md
  spec/abci/README.md
  spec/consensus/wal.md
  spec/p2p/README.md
  spec/rpc/README.md
Labels: spelling

#4877 chore: fix incorrect syntax in `scripts/dist.sh`
  scripts/dist.sh
Labels: hygiene

#4822 refactor: unify EnsurePeersPeriod configuration in PEX reactor
  p2p/pex/pex_reactor.go
  p2p/pex/pex_reactor_test.go
Labels: enhancement, p2p, hygiene

#4888 chore(deps): bump Go version to 1.23.5
  .github/workflows/go-version.env
  .golangci.yml
  README.md
  api/go.mod
  docs/tutorials/go-built-in.md
  docs/tutorials/go.md
  go.mod
  go.sum
  go.work
  test/e2e/docker/Dockerfile
  test/e2e/docker/Dockerfile.debug
Labels: dependencies, backport-to-v1.x

#4816 fix(pbts): hardening tests for overflows in `SynchronyParams`
  .changelog/unreleased/bug-fixes/4815-overflow-in-synchrony-params.md
  internal/consensus/pbts_test.go
  types/params.go
  types/params_test.go
  types/proposal_test.go
  types/validator_set_test.go
Labels: backport-to-v1.x, pbts
